import { Spark, Journey, FocusArea, InspirationEntry, Game, CommunityChallenge } from '@/types';

export const FOCUS_AREA_INFO: Record<FocusArea, { title: string; description: string; emoji: string }> = {
  communication: {
    title: 'Communication',
    description: 'Express yourself clearly and listen deeply',
    emoji: '💬',
  },
  trust: {
    title: 'Trust',
    description: 'Build reliability and emotional safety',
    emoji: '🤝',
  },
  play: {
    title: 'Play',
    description: 'Bring lightness, joy, and adventure',
    emoji: '🎨',
  },
  intimacy: {
    title: 'Intimacy',
    description: 'Deepen emotional and physical connection',
    emoji: '💕',
  },
  conflict: {
    title: 'Conflict',
    description: 'Navigate disagreements with grace',
    emoji: '⚡',
  },
  gratitude: {
    title: 'Gratitude',
    description: 'Appreciate what you have together',
    emoji: '🙏',
  },
  growth: {
    title: 'Growth',
    description: 'Evolve together as individuals and partners',
    emoji: '🌱',
  },
  boundaries: {
    title: 'Boundaries',
    description: 'Honor your needs and limits',
    emoji: '🛡️',
  },
  desire: {
    title: 'Desire',
    description: 'Keep attraction, tension, and novelty alive',
    emoji: '🔥',
  },
  intention: {
    title: 'Intention',
    description: 'Conscious choice, alignment, and intentional connection',
    emoji: '🧭',
  },
};

export const SEED_SPARKS: Spark[] = [
  {
    id: 'spark-1',
    title: 'The Two-Minute Check-In',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Most miscommunication happens when we assume rather than ask. A quick, intentional check-in can prevent hours of misunderstanding. The goal isn\'t to solve everything—just to sync.',
    starter: 'On a scale of 1-10, how much energy do you have today? What\'s taking up space in your mind?',
    action: 'Ask this question before making evening plans. Listen without trying to fix anything.',
    estTime: 2,
    tags: ['daily', 'quick', 'emotional-awareness'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-2',
    title: 'Gratitude Snapshot',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Our brains are wired to notice problems more than positives. Actively naming what\'s working rewires your attention toward connection rather than critique.',
    starter: 'Do you know one small thing you did recently that I didn\'t thank you for?',
    action: 'Text or tell them one specific thing you appreciated this week. Be concrete.',
    estTime: 3,
    tags: ['appreciation', 'positive'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-41',
    title: 'The Flirtation Reset',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Flirtation isn\'t just for new relationships—it\'s how we remind each other we\'re still choosing one another. A playful comment or lingering glance can reignite that early spark.',
    starter: 'When was the last time I made you feel butterflies?',
    action: 'Send a flirty text or give a playful compliment today. Make it feel a little risky—that\'s where desire lives.',
    estTime: 5,
    tags: ['flirtation', 'playfulness', 'attraction'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-3',
    title: 'The Curiosity Question',
    focusArea: 'communication',
    difficulty: 'deeper',
    lesson: 'When we\'ve known someone for a while, we stop asking questions. We assume we know the answers. But people evolve. Curiosity keeps relationships alive.',
    starter: 'What\'s something you\'re excited about right now that I might not know about?',
    action: 'Ask this question and give them 5 uninterrupted minutes to share. No advice, just curiosity.',
    estTime: 10,
    tags: ['listening', 'curiosity', 'deep-talk'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-4',
    title: 'The Repair Attempt',
    focusArea: 'conflict',
    difficulty: 'brave',
    lesson: 'Research shows that relationships aren\'t defined by whether you fight—but by how you repair afterward. A simple acknowledgment can reset the emotional temperature.',
    starter: 'I know things felt tense earlier. Can we talk about what happened?',
    action: 'Name one thing you could have done differently in a recent disagreement. Share it with humility.',
    estTime: 15,
    tags: ['repair', 'accountability', 'vulnerable'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-42',
    title: 'The Confidence Mirror',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Desire thrives when we feel confident. Reflecting what makes your partner magnetic reminds them they\'re desirable—not just loved, but wanted.',
    starter: 'Do you know something about you that I find irresistibly attractive?',
    action: 'Tell them one thing that makes them feel confident and desired. Be specific and genuine.',
    estTime: 5,
    tags: ['confidence', 'attraction', 'validation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-5',
    title: 'The Compliment Remix',
    focusArea: 'intimacy',
    difficulty: 'light',
    lesson: 'Compliments about character stick longer than compliments about appearance. Telling someone *who they are* to you builds deeper connection than telling them *what they look like*.',
    starter: 'Do you know what quality of yours makes me feel safe or seen?',
    action: 'Give them a compliment about their character, not their appearance. Be specific about how it impacts you.',
    estTime: 5,
    tags: ['affirmation', 'connection'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-6',
    title: 'The Playful Challenge',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Play isn\'t frivolous—it\'s how we stay young in our relationships. Shared laughter releases oxytocin, the bonding hormone. Fun is serious business.',
    starter: 'What\'s something ridiculous we could do together this week?',
    action: 'Do something silly together: dance in the kitchen, make up a handshake, try a tongue twister contest.',
    estTime: 10,
    tags: ['fun', 'laughter', 'lightness'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-7',
    title: 'The Boundary Conversation',
    focusArea: 'boundaries',
    difficulty: 'deeper',
    lesson: 'Boundaries aren\'t walls—they\'re the edges that let you show up fully. Saying "no" to what doesn\'t work makes space for deeper "yes" to what does.',
    starter: 'What\'s one thing I do that unintentionally drains you?',
    action: 'Share one boundary you need to set (or reset). Frame it as a gift to the relationship, not a criticism.',
    estTime: 12,
    tags: ['boundaries', 'honesty', 'needs'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-43',
    title: 'The Presence Practice',
    focusArea: 'desire',
    difficulty: 'deeper',
    lesson: 'Being fully present—without distractions—creates magnetic connection. Desire grows when someone feels truly seen and held in your attention.',
    starter: 'When do you feel most seen by me?',
    action: 'Create 15 minutes of phone-free, distraction-free time. Make eye contact. Listen deeply. Let presence do the work.',
    estTime: 15,
    tags: ['presence', 'attention', 'connection'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-8',
    title: 'The Growth Reflection',
    focusArea: 'growth',
    difficulty: 'deeper',
    lesson: 'Healthy relationships don\'t stay the same—they evolve. Checking in on how you\'ve both changed keeps you aligned rather than drifting apart.',
    starter: 'How do you think you\'ve grown in the past year? How have I supported (or missed) that growth?',
    action: 'Share one way you want to grow in the next 6 months. Ask how they want to support you.',
    estTime: 15,
    tags: ['growth', 'evolution', 'goals'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-9',
    title: 'The Trust Deposit',
    focusArea: 'trust',
    difficulty: 'light',
    lesson: 'Trust isn\'t built in grand gestures—it\'s built in tiny, consistent moments of follow-through. Every kept promise is a deposit in the trust bank.',
    starter: 'What\'s one small commitment I made that I haven\'t followed through on?',
    action: 'Identify one micro-promise you can make and keep this week. Follow through, no matter how small.',
    estTime: 5,
    tags: ['reliability', 'integrity', 'follow-through'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-10',
    title: 'The Appreciation Letter',
    focusArea: 'gratitude',
    difficulty: 'deeper',
    lesson: 'Written words carry weight that spoken words sometimes don\'t. A note can be revisited, saved, and returned to on hard days. It becomes evidence of love.',
    starter: 'If I wrote you a letter about why I value you, what would you most want to hear?',
    action: 'Write them a 3-sentence note of appreciation. Leave it somewhere they\'ll find it unexpectedly.',
    estTime: 8,
    tags: ['written', 'appreciation', 'surprise'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-44',
    title: 'The Novelty Adventure',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Novelty releases dopamine—the same chemical that creates attraction. Trying something new together reignites curiosity and excitement.',
    starter: 'What\'s something we\'ve never done that sounds exciting to you?',
    action: 'Pick one novel experience—a new restaurant, activity, or even a different route home. Schedule it this week.',
    estTime: 10,
    tags: ['novelty', 'spontaneity', 'adventure'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-11',
    title: 'The Future Vision',
    focusArea: 'growth',
    difficulty: 'brave',
    lesson: 'Couples who dream together stay together. Sharing what you hope for—not just what you\'re worried about—creates shared direction and excitement.',
    starter: 'What\'s one thing you hope our relationship looks like a year from now?',
    action: 'Share one hope you have for your relationship\'s future. Listen to theirs without judgment.',
    estTime: 20,
    tags: ['vision', 'future', 'dreams'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-12',
    title: 'The Stress Share',
    focusArea: 'communication',
    difficulty: 'deeper',
    lesson: 'Stress outside the relationship often leaks into it. Naming external pressures helps your partner understand your emotional climate without taking it personally.',
    starter: 'What\'s stressing you out that has nothing to do with us?',
    action: 'Share one external stressor you\'re carrying. Ask for what you need: space, listening, or help.',
    estTime: 10,
    tags: ['stress', 'support', 'external-factors'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-13',
    title: 'The Daily Debrief',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Consistent micro-connections prevent emotional distance. A quick daily debrief keeps you in sync even on busy days.',
    starter: 'What was the best part of your day today? What was the hardest?',
    action: 'Set a recurring 10-minute debrief time—maybe after dinner or before bed. Commit to it for one week.',
    estTime: 10,
    tags: ['daily', 'routine', 'sync'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-45',
    title: 'The Tension Tease',
    focusArea: 'desire',
    difficulty: 'brave',
    lesson: 'Anticipation is desire\'s fuel. Delaying gratification—whether through teasing, waiting, or building tension—makes connection more electric.',
    starter: 'What would make you want me more?',
    action: 'Create anticipation: send a suggestive message hours before seeing them, or start something and delay finishing it.',
    estTime: 5,
    tags: ['tension', 'anticipation', 'desire'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-26',
    title: 'The Silly Snapshot',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Playfulness keeps relationships from feeling like work. Laughter is the glue that holds serious conversations together.',
    starter: 'What\'s the silliest thing we could do together right now?',
    action: 'Do it. No excuses. Dance badly, make weird faces, invent a ridiculous game. Commit to the bit.',
    estTime: 5,
    tags: ['silly', 'spontaneous', 'fun'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-17',
    title: 'The Follow-Through Promise',
    focusArea: 'trust',
    difficulty: 'light',
    lesson: 'Trust grows in the gap between saying and doing. Small promises kept consistently outweigh grand gestures made rarely.',
    starter: 'What\'s one promise I made to you that I never quite followed through on?',
    action: 'Pick one small commitment to complete this week. Text them when it\'s done—accountability builds trust.',
    estTime: 5,
    tags: ['follow-through', 'reliability', 'promises'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-20',
    title: 'The Tiny Thanks',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Gratitude for the mundane transforms how we see our relationships. Thanking someone for "nothing special" makes them feel seen.',
    starter: 'What\'s something you do regularly that I don\'t thank you enough for?',
    action: 'Thank them for one boring, everyday thing they do. Be sincere. Watch how it shifts the mood.',
    estTime: 2,
    tags: ['daily', 'mundane', 'appreciation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-46',
    title: 'The Mystery Moment',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Mystery preserves intrigue. When we reveal everything, relationships can feel predictable. Keeping some parts private creates space for curiosity.',
    starter: 'What\'s something I don\'t know about you yet?',
    action: 'Share one small mystery about yourself—a hidden interest, memory, or dream. Leave them wanting to know more.',
    estTime: 8,
    tags: ['mystery', 'curiosity', 'intrigue'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-34',
    title: 'The Evolution Check',
    focusArea: 'growth',
    difficulty: 'deeper',
    lesson: 'People change. Checking in on each other\'s evolution prevents the trap of loving who someone was instead of who they\'re becoming.',
    starter: 'How do you feel like you\'ve changed in the last year? Do you feel like I see that change?',
    action: 'Share how you\'ve evolved. Ask them to reflect it back. Celebrate growth together.',
    estTime: 15,
    tags: ['evolution', 'change', 'awareness'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-24',
    title: 'The Eye Contact Challenge',
    focusArea: 'intimacy',
    difficulty: 'light',
    lesson: 'Eye contact builds neural synchrony and emotional attunement. It\'s the simplest intimacy hack that most couples skip.',
    starter: 'Can we hold eye contact for 60 seconds without speaking?',
    action: 'Set a timer. Hold eye contact. No laughing away. Notice what comes up—awkwardness, closeness, vulnerability.',
    estTime: 3,
    tags: ['eye-contact', 'presence', 'connection'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-30',
    title: 'The Cooling-Off Protocol',
    focusArea: 'conflict',
    difficulty: 'deeper',
    lesson: 'Knowing when to pause prevents escalation. A time-out isn\'t avoidance—it\'s strategic emotional regulation.',
    starter: 'What signal can we use when one of us needs to cool off during a disagreement?',
    action: 'Agree on a cooling-off protocol: a word, gesture, or time limit. Practice using it this week.',
    estTime: 10,
    tags: ['de-escalation', 'time-out', 'regulation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-47',
    title: 'The Validation Gift',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Feeling wanted is different from feeling loved. Desire requires active validation—being told, shown, and reminded that you\'re chosen.',
    starter: 'Do you know how much I still want you?',
    action: 'Tell them explicitly that you choose them, desire them, and are still attracted to them. Make it feel intentional.',
    estTime: 5,
    tags: ['validation', 'wanted', 'affirmation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-39',
    title: 'The Space Request',
    focusArea: 'boundaries',
    difficulty: 'light',
    lesson: 'Asking for space isn\'t rejection—it\'s self-care. Partners who honor space create safety for autonomy and togetherness.',
    starter: 'Is there a time of day or activity where you need more space from me?',
    action: 'Share one space boundary. Commit to honoring it without taking it personally.',
    estTime: 8,
    tags: ['space', 'autonomy', 'alone-time'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-14',
    title: 'The Appreciation Amplifier',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Being specific with appreciation makes it land deeper. Vague praise feels nice; detailed recognition feels transformative.',
    starter: 'What did I do recently that made your day a little easier or better?',
    action: 'Practice giving one ultra-specific compliment today. Name the action, when it happened, and how it made you feel.',
    estTime: 5,
    tags: ['appreciation', 'specific', 'positive'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-27',
    title: 'The Adventure Brainstorm',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Novelty reignites attraction. Planning small adventures together creates anticipation and shared excitement.',
    starter: 'What\'s one place or activity we\'ve never tried that sounds fun to you?',
    action: 'Pick one and schedule it within the next two weeks. Even tiny adventures count.',
    estTime: 10,
    tags: ['adventure', 'novelty', 'planning'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-48',
    title: 'The Chosen Ritual',
    focusArea: 'desire',
    difficulty: 'deeper',
    lesson: 'Desire fades when we stop pursuing. Creating rituals of intentional pursuit—choosing each other actively—keeps relationships from feeling like autopilot.',
    starter: 'How can I make you feel more pursued and chosen?',
    action: 'Create a weekly ritual of intentional pursuit: plan a surprise, initiate a date, or do something that shows active effort.',
    estTime: 20,
    tags: ['intention', 'chosen', 'pursuit'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-21',
    title: 'The Gratitude Rewind',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Revisiting past gratitude deepens current appreciation. Memory + emotion = lasting connection.',
    starter: 'Do you know what moment from our early days I\'m still grateful for?',
    action: 'Share one memory you\'re grateful for. Relive it together for 5 minutes—details, feelings, everything.',
    estTime: 8,
    tags: ['memories', 'nostalgia', 'appreciation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-18',
    title: 'The Transparency Practice',
    focusArea: 'trust',
    difficulty: 'deeper',
    lesson: 'Radical transparency—even when uncomfortable—builds long-term safety. Hiding small truths erodes trust over time.',
    starter: 'Is there anything small you\'ve been keeping from me to avoid conflict or judgment?',
    action: 'Share one small truth you\'ve been holding back. Frame it gently, but frame it honestly.',
    estTime: 12,
    tags: ['honesty', 'transparency', 'vulnerability'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-35',
    title: 'The Dream Support',
    focusArea: 'growth',
    difficulty: 'light',
    lesson: 'Supporting your partner\'s dreams—even the impractical ones—shows you believe in their potential, not just their productivity.',
    starter: 'What\'s one dream or goal you have that you don\'t talk about much?',
    action: 'Ask how you can support it. Even small encouragement—time, space, or just belief—matters.',
    estTime: 10,
    tags: ['dreams', 'support', 'belief'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-31',
    title: 'The Fight Playback',
    focusArea: 'conflict',
    difficulty: 'brave',
    lesson: 'Rewatching a fight from the other\'s perspective reveals blind spots. Curiosity about their experience fosters empathy.',
    starter: 'Can you walk me through our last argument from your perspective? I want to understand how you experienced it.',
    action: 'Listen without defending. Ask clarifying questions. Validate what you hear, even if you don\'t fully agree.',
    estTime: 20,
    tags: ['perspective', 'empathy', 'replay'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-23',
    title: 'The Touch Check-In',
    focusArea: 'intimacy',
    difficulty: 'deeper',
    lesson: 'Not all touch means the same thing. Understanding what physical affection feels connective vs. obligatory matters.',
    starter: 'What kind of touch from me makes you feel most loved and connected?',
    action: 'Practice that type of touch intentionally today. Notice if it feels different when it\'s conscious.',
    estTime: 10,
    tags: ['physical', 'touch', 'awareness'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-15',
    title: 'The Permission Pause',
    focusArea: 'communication',
    difficulty: 'deeper',
    lesson: 'Sometimes we need permission to be honest without consequences. Creating safety for vulnerability strengthens trust.',
    starter: 'Is there something you\'ve been hesitant to tell me? I want to hear it without judgment.',
    action: 'Create a 15-minute space where either partner can share something vulnerable. Listen, validate, don\'t fix.',
    estTime: 15,
    tags: ['vulnerability', 'honesty', 'safety'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-38',
    title: 'The "Yes" Threshold',
    focusArea: 'boundaries',
    difficulty: 'deeper',
    lesson: 'Saying yes when you mean no breeds resentment. Knowing your threshold helps you honor your capacity without guilt.',
    starter: 'What\'s something you said yes to recently that you wish you\'d said no to?',
    action: 'Share one example. Talk about what made it hard to say no. Practice saying "not right now" together.',
    estTime: 10,
    tags: ['yes', 'no', 'capacity'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-22',
    title: 'The Surprise Acknowledgment',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Unexpected appreciation hits differently. Surprise gratitude interrupts routine and reignites affection.',
    starter: 'Do you know what you\'ve gotten better at that I haven\'t acknowledged yet?',
    action: 'Send them a voice note or handwritten note thanking them for their growth. Be specific.',
    estTime: 5,
    tags: ['growth', 'surprise', 'acknowledgment'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-28',
    title: 'The Inside Joke Refresh',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Inside jokes are relational currency. They remind you that you share a world no one else understands.',
    starter: 'What\'s our funniest inside joke? When did it start?',
    action: 'Retell the origin story. Laugh together. Create a new inside joke this week.',
    estTime: 8,
    tags: ['inside-jokes', 'humor', 'memories'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-36',
    title: 'The Skill Swap',
    focusArea: 'growth',
    difficulty: 'light',
    lesson: 'Teaching each other new things builds admiration and keeps curiosity alive. You become students of each other.',
    starter: 'What\'s one thing you know how to do that you could teach me?',
    action: 'Schedule a mini lesson. Let them teach you something—cooking, a game, a skill. Be a willing learner.',
    estTime: 30,
    tags: ['teaching', 'learning', 'skills'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-19',
    title: 'The Trust Temperature Check',
    focusArea: 'trust',
    difficulty: 'deeper',
    lesson: 'Trust isn\'t binary—it fluctuates. Checking in on trust levels prevents silent erosion and opens repair opportunities.',
    starter: 'On a scale of 1-10, how much do you trust me right now? What would move it closer to 10?',
    action: 'Answer honestly, then listen without defensiveness. Pick one action to take based on their answer.',
    estTime: 15,
    tags: ['check-in', 'trust-levels', 'honest'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-32',
    title: 'The Trigger Map',
    focusArea: 'conflict',
    difficulty: 'deeper',
    lesson: 'Most fights aren\'t about the thing—they\'re about the tender spot underneath. Mapping triggers prevents repeat cycles.',
    starter: 'What\'s something I say or do that consistently triggers you, even if it seems small?',
    action: 'Share one trigger each. Talk about why it lands that way. Commit to being gentler around it.',
    estTime: 15,
    tags: ['triggers', 'patterns', 'awareness'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-25',
    title: 'The Desire Discussion',
    focusArea: 'intimacy',
    difficulty: 'brave',
    lesson: 'Talking about desire openly—not just sex, but all forms of wanting—normalizes longing and prevents resentment.',
    starter: 'What\'s something you desire from me—emotionally, physically, or otherwise—that you don\'t often ask for?',
    action: 'Share one desire. Be specific, vulnerable, and open to hearing theirs in return.',
    estTime: 20,
    tags: ['desire', 'vulnerability', 'honesty'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-16',
    title: 'The Request vs. Demand Check',
    focusArea: 'communication',
    difficulty: 'deeper',
    lesson: 'How we ask matters as much as what we ask for. Requests invite partnership; demands create defensiveness.',
    starter: 'Is there a way I ask for things that feels more like pressure than collaboration?',
    action: 'Reframe one recent demand as a request. Notice how you both feel when needs are expressed with openness.',
    estTime: 8,
    tags: ['needs', 'requests', 'tone'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-29',
    title: 'The Competitive Connection',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Healthy competition adds spice. Friendly rivalry keeps things dynamic as long as you\'re laughing at the end.',
    starter: 'Want to compete in something silly—cooking, a game, or a random challenge?',
    action: 'Pick a low-stakes competition. Winner gets to pick the next date night or meal.',
    estTime: 30,
    tags: ['competition', 'games', 'fun'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-40',
    title: 'The Boundary Repair',
    focusArea: 'boundaries',
    difficulty: 'brave',
    lesson: 'When boundaries are crossed, repair matters more than perfection. Acknowledging the breach and recommitting builds trust.',
    starter: 'Is there a boundary I crossed recently that we didn\'t fully address?',
    action: 'Name it. Apologize specifically. Ask what repair looks like. Follow through.',
    estTime: 15,
    tags: ['repair', 'accountability', 'trust'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-37',
    title: 'The Failure Share',
    focusArea: 'growth',
    difficulty: 'brave',
    lesson: 'Sharing failures without shame normalizes imperfection and models self-compassion. It gives permission to be human.',
    starter: 'What\'s something you tried recently that didn\'t work out? How did it feel?',
    action: 'Share a recent failure. Talk about what you learned. Offer compassion, not solutions.',
    estTime: 12,
    tags: ['failure', 'vulnerability', 'compassion'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-33',
    title: 'The Apology Upgrade',
    focusArea: 'conflict',
    difficulty: 'deeper',
    lesson: 'A real apology includes ownership, impact acknowledgment, and a changed behavior plan. "Sorry" alone isn\'t enough.',
    starter: 'What does a meaningful apology look and feel like to you?',
    action: 'Reframe a past apology using their criteria. Say it out loud or write it down.',
    estTime: 12,
    tags: ['apology', 'repair', 'accountability'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-ed-comm-1',
    title: 'The First Layer',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Early dating is about revealing who you are in small doses. Sharing your day-to-day thoughts builds comfort without overwhelming someone new.',
    starter: 'What made you smile today?',
    action: 'Share one small, genuine thing about your day. Keep it light but real.',
    estTime: 3,
    tags: ['getting-to-know', 'daily', 'light'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-comm-2',
    title: 'The Interest Invite',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Asking about someone\'s passions shows genuine curiosity. People light up when talking about what they love—it\'s where you see their true self.',
    starter: 'What\'s something you love doing that most people don\'t know about?',
    action: 'Ask this question and give them space to share. Follow up with one curious question.',
    estTime: 5,
    tags: ['curiosity', 'interests', 'getting-to-know'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-comm-3',
    title: 'The Energy Read',
    focusArea: 'communication',
    difficulty: 'light',
    lesson: 'Early on, checking in shows you care about their well-being, not just the connection. It builds trust without pressure.',
    starter: 'How are you feeling today, really?',
    action: 'Check in genuinely. Listen without trying to fix or over-analyze.',
    estTime: 3,
    tags: ['check-in', 'emotional-awareness', 'care'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-trust-1',
    title: 'The Small Promise',
    focusArea: 'trust',
    difficulty: 'light',
    lesson: 'Trust in early dating starts with tiny commitments. Following through on small things shows reliability before the stakes get high.',
    starter: 'Is there something small I said I\'d do that I haven\'t done yet?',
    action: 'Keep one small promise this week. Text when you say you will. Show up on time.',
    estTime: 2,
    tags: ['reliability', 'follow-through', 'consistency'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-trust-2',
    title: 'The Honesty Signal',
    focusArea: 'trust',
    difficulty: 'light',
    lesson: 'Sharing something real—even if small—signals that you\'re not performing. Authenticity builds trust faster than perfection.',
    starter: 'Do you want to know something honest about how I\'m feeling?',
    action: 'Share one small, honest thing. It doesn\'t have to be deep—just true.',
    estTime: 5,
    tags: ['honesty', 'authenticity', 'vulnerability'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-trust-3',
    title: 'The Consistency Check',
    focusArea: 'trust',
    difficulty: 'light',
    lesson: 'People notice when your words and actions align. Early trust is built through consistency, not grand gestures.',
    starter: 'What\'s one thing I\'ve done that made you feel like you could trust me?',
    action: 'Ask this question. Listen to what matters to them, then keep doing it.',
    estTime: 5,
    tags: ['consistency', 'reliability', 'trust-building'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-conflict-1',
    title: 'The Gentle Clarify',
    focusArea: 'conflict',
    difficulty: 'light',
    lesson: 'In early dating, small miscommunications can spiral. Clarifying gently prevents assumptions from building walls.',
    starter: 'I might have misunderstood—can you help me understand what you meant?',
    action: 'If something feels off, ask for clarity instead of assuming. Stay curious, not defensive.',
    estTime: 5,
    tags: ['clarification', 'misunderstanding', 'curiosity'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-conflict-2',
    title: 'The Pace Conversation',
    focusArea: 'conflict',
    difficulty: 'deeper',
    lesson: 'Different paces in early dating cause friction. Naming it openly prevents resentment before it starts.',
    starter: 'How are you feeling about the pace of us getting to know each other?',
    action: 'Check in about pacing. Share yours, listen to theirs, find a middle ground.',
    estTime: 8,
    tags: ['pacing', 'expectations', 'alignment'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-conflict-3',
    title: 'The Early Boundary',
    focusArea: 'conflict',
    difficulty: 'light',
    lesson: 'Setting small boundaries early shows self-respect. It also teaches the other person how to treat you.',
    starter: 'There\'s something small I\'d like to share about what works for me—can I tell you?',
    action: 'Name one small preference or boundary. Frame it as information, not a demand.',
    estTime: 5,
    tags: ['boundaries', 'preferences', 'self-respect'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-play-1',
    title: 'The Laugh Test',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Humor compatibility matters. Shared laughter in early dating signals comfort and chemistry.',
    starter: 'What\'s something that always makes you laugh?',
    action: 'Share something funny—a video, story, or memory. See if your humor aligns.',
    estTime: 5,
    tags: ['humor', 'laughter', 'connection'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-play-2',
    title: 'The Spontaneous Invite',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Low-stakes spontaneity shows playfulness without pressure. It\'s how you learn if someone is fun or rigid.',
    starter: 'Want to do something random right now—even if it\'s small?',
    action: 'Suggest something spontaneous: a walk, trying a new coffee shop, or a silly game.',
    estTime: 10,
    tags: ['spontaneity', 'adventure', 'low-stakes'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-play-3',
    title: 'The Silly Reveal',
    focusArea: 'play',
    difficulty: 'light',
    lesson: 'Sharing something goofy about yourself breaks down walls. It shows you don\'t take yourself too seriously.',
    starter: 'Want to know something ridiculous about me?',
    action: 'Share one silly habit, guilty pleasure, or embarrassing story. Keep it light.',
    estTime: 5,
    tags: ['humor', 'vulnerability', 'authenticity'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-gratitude-1',
    title: 'The Small Acknowledgment',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Noticing effort early on makes someone feel seen. Appreciation in the beginning sets a positive tone.',
    starter: 'Do you know what you did recently that I really appreciated?',
    action: 'Name one small thing they did that you noticed. Be specific.',
    estTime: 2,
    tags: ['appreciation', 'noticing', 'effort'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-gratitude-2',
    title: 'The Quality Compliment',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'Complimenting character over appearance signals depth. It shows you\'re paying attention to who they are, not just what they look like.',
    starter: 'Do you know what quality of yours stands out to me?',
    action: 'Give them a compliment about their personality, humor, or the way they treat people.',
    estTime: 3,
    tags: ['compliment', 'character', 'depth'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-gratitude-3',
    title: 'The Effort Notice',
    focusArea: 'gratitude',
    difficulty: 'light',
    lesson: 'When someone shows effort in early dating, acknowledging it reinforces positive behavior.',
    starter: 'I noticed you did [specific thing]—that meant a lot to me.',
    action: 'Text or tell them one thing they did that showed effort. Be direct and warm.',
    estTime: 2,
    tags: ['effort', 'acknowledgment', 'reinforcement'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-intimacy-1',
    title: 'The Comfortable Silence',
    focusArea: 'intimacy',
    difficulty: 'light',
    lesson: 'Early intimacy isn\'t about constant talking—it\'s about being comfortable in quiet moments together.',
    starter: 'Can we just sit here for a minute without talking?',
    action: 'Practice being together in silence. Notice if it feels awkward or comfortable.',
    estTime: 5,
    tags: ['silence', 'presence', 'comfort'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-intimacy-2',
    title: 'The Vulnerability Share',
    focusArea: 'intimacy',
    difficulty: 'deeper',
    lesson: 'Sharing something real creates emotional closeness. Vulnerability in small doses builds intimacy without overwhelming.',
    starter: 'Can I share something I don\'t tell most people?',
    action: 'Share one thing that feels a little vulnerable. See how they respond.',
    estTime: 8,
    tags: ['vulnerability', 'sharing', 'closeness'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-intimacy-3',
    title: 'The Presence Practice',
    focusArea: 'intimacy',
    difficulty: 'light',
    lesson: 'Being fully present—not on your phone, not distracted—signals respect and interest. It\'s how emotional intimacy begins.',
    starter: 'Let\'s put our phones away for the next 20 minutes.',
    action: 'Create phone-free time together. Notice how the conversation deepens.',
    estTime: 20,
    tags: ['presence', 'phones-away', 'attention'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-growth-1',
    title: 'The Dream Share',
    focusArea: 'growth',
    difficulty: 'light',
    lesson: 'Learning someone\'s goals shows you care about their future, not just their present. It\'s a sign of serious interest.',
    starter: 'What\'s something you\'re working toward right now?',
    action: 'Ask about their goals or dreams. Listen without offering advice.',
    estTime: 8,
    tags: ['goals', 'dreams', 'future'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-growth-2',
    title: 'The Learning Curiosity',
    focusArea: 'growth',
    difficulty: 'light',
    lesson: 'Asking what someone is learning reveals their curiosity and growth mindset. It\'s a deeper question than it seems.',
    starter: 'What\'s something new you\'ve been learning or exploring lately?',
    action: 'Ask this question and engage with their answer. Share yours too.',
    estTime: 10,
    tags: ['learning', 'curiosity', 'growth-mindset'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-growth-3',
    title: 'The Support Signal',
    focusArea: 'growth',
    difficulty: 'light',
    lesson: 'Encouraging someone\'s goals early on shows you\'re invested in their growth, not just what they can give you.',
    starter: 'How can I support what you\'re working on?',
    action: 'Ask how you can support their current goal. Then do one small thing to show you meant it.',
    estTime: 5,
    tags: ['support', 'encouragement', 'partnership'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-boundaries-1',
    title: 'The Pace Preference',
    focusArea: 'boundaries',
    difficulty: 'light',
    lesson: 'Everyone has different comfort levels with how fast things move. Stating yours prevents misalignment.',
    starter: 'I want to be honest about what pace feels comfortable for me—can we talk about that?',
    action: 'Share your pacing preference. Ask about theirs. Find alignment.',
    estTime: 8,
    tags: ['pacing', 'comfort', 'alignment'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-boundaries-2',
    title: 'The Communication Need',
    focusArea: 'boundaries',
    difficulty: 'light',
    lesson: 'Sharing how you prefer to communicate (texting, calling, in person) prevents frustration and mismatched expectations.',
    starter: 'How do you like to stay in touch between seeing each other?',
    action: 'Share your communication style. Ask about theirs. Agree on what works for both.',
    estTime: 5,
    tags: ['communication', 'texting', 'preferences'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-boundaries-3',
    title: 'The Solo Time Need',
    focusArea: 'boundaries',
    difficulty: 'light',
    lesson: 'Being upfront about needing alone time shows self-awareness. It also prevents clinginess or distance from becoming issues.',
    starter: 'I want you to know that I sometimes need solo time to recharge—does that make sense to you?',
    action: 'Share your need for alone time. Normalize it as healthy, not rejection.',
    estTime: 5,
    tags: ['alone-time', 'recharge', 'self-care'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-desire-1',
    title: 'The Flirt Opener',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Light flirting keeps attraction alive without pressure. It signals interest while keeping things playful.',
    starter: 'I\'ve been thinking about you today.',
    action: 'Send a flirty text or give a playful compliment. Keep it light but intentional.',
    estTime: 2,
    tags: ['flirtation', 'attraction', 'playful'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-desire-2',
    title: 'The Attraction Acknowledgment',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Naming attraction directly—without being over the top—creates tension and clarity. It\'s honest and magnetic.',
    starter: 'I\'m really attracted to you. Just wanted you to know.',
    action: 'Tell them you\'re attracted to them. Say it simply and confidently.',
    estTime: 2,
    tags: ['attraction', 'honesty', 'directness'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-ed-desire-3',
    title: 'The Anticipation Build',
    focusArea: 'desire',
    difficulty: 'light',
    lesson: 'Building anticipation between dates keeps desire alive. A thoughtful text about looking forward to seeing them creates excitement.',
    starter: 'I\'m really looking forward to seeing you [specific day].',
    action: 'Send a message before your next date that shows you\'re excited. Be specific about what you\'re looking forward to.',
    estTime: 2,
    tags: ['anticipation', 'excitement', 'desire'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-1',
    title: 'The Why Check',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Early connection feels safer when intentions are shared plainly, not guessed or disguised behind casual ambiguity.',
    starter: 'What made you interested in dating right now?',
    action: 'Share your intention honestly without selling yourself or predicting the future.',
    estTime: 5,
    tags: ['intention', 'honesty', 'clarity'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-2',
    title: 'The Curiosity Line',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Intentional curiosity builds connection faster than performance, inviting real interest instead of rehearsed answers and safe scripts.',
    starter: 'What\'s something you\'re genuinely curious about lately?',
    action: 'Ask a follow-up question that shows you\'re listening, not impressing.',
    estTime: 5,
    tags: ['intention', 'curiosity', 'listening'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-3',
    title: 'The Transparency Moment',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Small moments of honesty build early trust, creating clarity without oversharing or forcing emotional intimacy too soon.',
    starter: 'What\'s something you\'re learning about yourself right now?',
    action: 'Share one true thing that feels safe but real.',
    estTime: 5,
    tags: ['intention', 'honesty', 'trust'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-4',
    title: 'The Time Lens',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Naming time expectations early prevents misalignment, reduces pressure, and helps both people relax into a shared pace.',
    starter: 'How do you usually like things to unfold when you\'re getting to know someone?',
    action: 'Name your pace without comparing it to past relationships.',
    estTime: 5,
    tags: ['intention', 'pacing', 'alignment'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-5',
    title: 'The Signal Check',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Clarifying signals early reduces guessing games, protects emotional safety, and helps interest feel mutual and respectful.',
    starter: 'What helps you feel someone\'s genuinely interested?',
    action: 'Reflect back what you heard before sharing your own answer.',
    estTime: 5,
    tags: ['intention', 'signals', 'clarity'],
    createdBy: 'system',
    relationshipStage: 'early',
  },
  {
    id: 'spark-intention-6',
    title: 'The Growth Aim',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Intentional relationships evolve when both partners name what they\'re building together and revisit it regularly with care.',
    starter: 'What kind of growth feels most important for us right now?',
    action: 'Choose one shared focus for the next month.',
    estTime: 10,
    tags: ['intention', 'growth', 'partnership'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-7',
    title: 'The Conflict Compass',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Intentional conflict keeps disagreements anchored in love, helping you repair faster instead of proving points or winning.',
    starter: 'What do you want us to protect when we disagree?',
    action: 'Agree on one value to anchor future conflicts.',
    estTime: 10,
    tags: ['intention', 'conflict', 'values'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-8',
    title: 'The Effort Mirror',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Intentional effort stays visible when partners reflect what feels supportive rather than assuming effort is automatically understood.',
    starter: 'What effort from me has felt most meaningful lately?',
    action: 'Name one effort you\'ll continue intentionally this week.',
    estTime: 10,
    tags: ['intention', 'effort', 'appreciation'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-9',
    title: 'The Future Tone',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Intentional couples shape the future by agreeing on tone, not just plans, goals, or logistics.',
    starter: 'How do you want our future to feel, not just look?',
    action: 'Choose one word that defines your shared direction.',
    estTime: 10,
    tags: ['intention', 'future', 'vision'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-10',
    title: 'The Presence Choice',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Choosing presence intentionally strengthens connection, even during busy seasons where attention is often unintentionally divided.',
    starter: 'When do you feel I\'m most present with you?',
    action: 'Create one distraction-free moment this week.',
    estTime: 10,
    tags: ['intention', 'presence', 'attention'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-11',
    title: 'The Support Lens',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Intentional support adapts over time, honoring changing needs rather than relying on outdated assumptions.',
    starter: 'What kind of support feels best to you right now?',
    action: 'Adjust one support habit based on their answer.',
    estTime: 10,
    tags: ['intention', 'support', 'adaptability'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-12',
    title: 'The Relationship North Star',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Clear intention keeps relationships aligned by reminding partners what matters most when emotions or circumstances fluctuate.',
    starter: 'What do you want our relationship to always stand for?',
    action: 'Write down one shared value and revisit it monthly.',
    estTime: 10,
    tags: ['intention', 'values', 'alignment'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-13',
    title: 'The Choice Reminder',
    focusArea: 'intention',
    difficulty: 'light',
    lesson: 'Long-term love stays intentional when partners remember connection is a daily choice, not an automatic outcome.',
    starter: 'What makes choosing each other feel easy lately?',
    action: 'Do one small choosing-you action today.',
    estTime: 5,
    tags: ['intention', 'choice', 'commitment'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
  {
    id: 'spark-intention-14',
    title: 'The Alignment Check',
    focusArea: 'intention',
    difficulty: 'deeper',
    lesson: 'Regular alignment prevents silent drifting by creating space to course-correct together without blame or urgency.',
    starter: 'Where do you feel most aligned with me right now?',
    action: 'Name one area you want to realign gently.',
    estTime: 10,
    tags: ['intention', 'alignment', 'connection'],
    createdBy: 'system',
    relationshipStage: 'established',
  },
];

export const SEED_JOURNEYS: Journey[] = [
  {
    id: 'journey-1',
    title: '7 Days of Better Questions',
    days: 7,
    overview: 'Transform your conversations with one powerful question each day. Great for couples who want to go deeper without feeling overwhelmed.',
    focusAreas: ['communication', 'intimacy'],
    difficulty: 'light',
    slug: 'better-questions',
    journeyType: 'devotional',
    durationDays: 7,
    steps: [
      {
        dayIndex: 0,
        title: 'The Energy Check',
        sparkId: 'spark-1',
      },
      {
        dayIndex: 1,
        title: 'The Curiosity Opener',
        sparkId: 'spark-3',
      },
      {
        dayIndex: 2,
        title: 'The Stress Sync',
        sparkId: 'spark-12',
      },
      {
        dayIndex: 3,
        title: 'The Appreciation Moment',
        sparkId: 'spark-2',
      },
      {
        dayIndex: 4,
        title: 'The Boundary Conversation',
        sparkId: 'spark-7',
      },
      {
        dayIndex: 5,
        title: 'The Growth Check-In',
        sparkId: 'spark-8',
      },
      {
        dayIndex: 6,
        title: 'The Future Vision',
        sparkId: 'spark-11',
      },
    ],
  },
  {
    id: 'journey-2',
    title: 'Rebuilding Trust',
    days: 14,
    overview: 'A gentle, structured path to rebuild trust after a breach. Focus on small, consistent actions and honest conversations.',
    focusAreas: ['trust', 'conflict', 'boundaries'],
    difficulty: 'brave',
    slug: 'rebuild-trust',
    journeyType: 'devotional',
    durationDays: 14,
    steps: [
      {
        dayIndex: 0,
        title: 'Acknowledge the Hurt',
        customLesson: 'Trust is rebuilt through acknowledgment, not avoidance. The first step is naming what happened without defensiveness.',
        customStarter: 'Can you help me understand how what happened affected you?',
        customAction: 'Listen to their pain for 10 minutes without explaining, defending, or minimizing.',
      },
      {
        dayIndex: 1,
        title: 'The Trust Deposit',
        sparkId: 'spark-9',
      },
      {
        dayIndex: 2,
        title: 'Share Your Why',
        customLesson: 'Trust requires understanding context, not just actions. Explaining your "why" helps your partner see the fuller picture.',
        customStarter: 'Here\'s what was happening for me at the time...',
        customAction: 'Share the context of what led to the breach, taking full responsibility without blaming circumstances.',
      },
      {
        dayIndex: 3,
        title: 'Name the Need',
        customLesson: 'Often, breaches happen when unmet needs go unspoken. Identifying the core need helps prevent future hurt.',
        customStarter: 'What need was I trying to meet? What need did I ignore?',
        customAction: 'Identify the unmet need that contributed to the breach. Share it honestly.',
      },
      {
        dayIndex: 4,
        title: 'Set a Boundary',
        sparkId: 'spark-7',
      },
      {
        dayIndex: 5,
        title: 'The Repair Plan',
        customLesson: 'Trust is rebuilt through consistent actions, not just words. A clear plan creates accountability.',
        customStarter: 'What specific actions would help you start to trust me again?',
        customAction: 'Co-create a short list of 3 specific actions you\'ll take to rebuild trust. Write them down.',
      },
      {
        dayIndex: 6,
        title: 'Rest Day: Reflect',
        customLesson: 'Rebuilding trust is emotionally taxing. Rest is part of the work.',
        customStarter: 'How are you feeling about this process so far?',
        customAction: 'Journal privately about how you\'re feeling. Take a break from heavy conversations today.',
      },
      {
        dayIndex: 7,
        title: 'The Check-In',
        sparkId: 'spark-1',
      },
      {
        dayIndex: 8,
        title: 'The Apology Redux',
        customLesson: 'A true apology includes: what you did, the impact it had, and what you\'ll do differently. Repeat if needed.',
        customStarter: 'I know I\'ve apologized before, but I want to make sure you truly feel heard.',
        customAction: 'Offer a fuller apology that includes all three elements. Ask if there\'s anything they still need to hear.',
      },
      {
        dayIndex: 9,
        title: 'Celebrate a Win',
        customLesson: 'Even small progress deserves acknowledgment. Celebrate kept promises and moments of reconnection.',
        customStarter: 'What\'s one thing I\'ve done this week that felt like progress?',
        customAction: 'Name one micro-win from this process. Acknowledge the effort it took.',
      },
      {
        dayIndex: 10,
        title: 'The Vulnerability Share',
        customLesson: 'Rebuilding trust requires mutual vulnerability. Share what you\'re afraid of in this process.',
        customStarter: 'I\'m afraid that...',
        customAction: 'Share one fear you have about rebuilding trust. Be honest about your vulnerability.',
      },
      {
        dayIndex: 11,
        title: 'The Gratitude Shift',
        sparkId: 'spark-10',
      },
      {
        dayIndex: 12,
        title: 'The Future Commitment',
        customLesson: 'Trust is rebuilt when both people believe in the relationship\'s future. Naming your commitment matters.',
        customStarter: 'Here\'s why I\'m committed to working through this...',
        customAction: 'Share your commitment to the relationship and to ongoing growth. Be specific.',
      },
      {
        dayIndex: 13,
        title: 'The New Beginning',
        customLesson: 'Rebuilding trust doesn\'t erase the past, but it can create a new chapter. Decide together what comes next.',
        customStarter: 'What do we both need to move forward from here?',
        customAction: 'Co-create a ritual or symbol that marks this new chapter. It could be as simple as a shared meal.',
      },
    ],
  },
  {
    id: 'journey-3',
    title: '30-Day Relationship Renaissance',
    days: 30,
    overview: 'A complete refresh for couples who feel stuck in a rut. Rotate through all focus areas with escalating depth and playfulness.',
    focusAreas: ['communication', 'play', 'intimacy', 'gratitude', 'growth'],
    difficulty: 'deeper',
    slug: 'renaissance',
    journeyType: 'devotional',
    durationDays: 30,
    steps: Array.from({ length: 30 }, (_, i) => {
      const sparkIds = ['spark-1', 'spark-2', 'spark-3', 'spark-5', 'spark-6', 'spark-8', 'spark-10', 'spark-11'];
      return {
        dayIndex: i,
        title: `Day ${i + 1}: ${['Connection', 'Gratitude', 'Curiosity', 'Play', 'Growth'][i % 5]}`,
        sparkId: sparkIds[i % sparkIds.length],
      };
    }),
  },
  {
    id: 'journey-4',
    title: 'Everyday Appreciation',
    days: 10,
    overview: 'Build a daily habit of noticing, naming, and celebrating the little things your partner does.',
    focusAreas: ['gratitude', 'communication'],
    difficulty: 'light',
    slug: 'everyday-appreciation',
    journeyType: 'devotional',
    durationDays: 10,
    steps: [
      {
        dayIndex: 0,
        title: 'Notice the Small Things',
        sparkId: 'spark-2',
      },
      {
        dayIndex: 1,
        title: 'Express Gratitude',
        sparkId: 'spark-10',
      },
      {
        dayIndex: 2,
        title: 'The Compliment Remix',
        sparkId: 'spark-5',
      },
      {
        dayIndex: 3,
        title: 'Daily Check-In',
        sparkId: 'spark-1',
      },
      {
        dayIndex: 4,
        title: 'Appreciation Snapshot',
        sparkId: 'spark-2',
      },
      {
        dayIndex: 5,
        title: 'The Written Note',
        sparkId: 'spark-10',
      },
      {
        dayIndex: 6,
        title: 'Character Compliment',
        sparkId: 'spark-5',
      },
      {
        dayIndex: 7,
        title: 'Energy Check',
        sparkId: 'spark-1',
      },
      {
        dayIndex: 8,
        title: 'Gratitude Moment',
        sparkId: 'spark-2',
      },
      {
        dayIndex: 9,
        title: 'Celebration Day',
        sparkId: 'spark-10',
      },
    ],
  },
  {
    id: 'workshop-1',
    title: 'Conflict Reset Workshop',
    days: 1,
    overview: 'A one-session reset to slow down heated moments, clarify needs, and practice repair together.',
    focusAreas: ['conflict', 'communication'],
    difficulty: 'brave',
    slug: 'conflict-reset',
    journeyType: 'workshop',
    durationMinutes: 15,
    steps: [
      {
        dayIndex: 0,
        title: 'Conflict Reset',
        sparkId: 'spark-4',
      },
    ],
  },
  {
    id: 'workshop-2',
    title: 'Love Languages Deep Dive',
    days: 1,
    overview: 'Explore each partner\'s primary love languages and plan 3 simple ways to speak them this week.',
    focusAreas: ['intimacy', 'communication'],
    difficulty: 'light',
    slug: 'love-languages',
    journeyType: 'workshop',
    durationMinutes: 12,
    steps: [
      {
        dayIndex: 0,
        title: 'Love Languages',
        sparkId: 'spark-5',
      },
    ],
  },
  {
    id: 'workshop-3',
    title: 'Story of Us Session',
    days: 1,
    overview: 'Map out your relationship origin story, high points, and turning points in one guided session.',
    focusAreas: ['communication', 'gratitude'],
    difficulty: 'deeper',
    slug: 'story-of-us',
    journeyType: 'workshop',
    durationMinutes: 18,
    steps: [
      {
        dayIndex: 0,
        title: 'Story of Us',
        sparkId: 'spark-3',
      },
    ],
  },
  {
    id: 'workshop-4',
    title: 'Future Vision Check-In',
    days: 1,
    overview: 'Align on 3–5 hopes for the next year and choose one small action you can take this week.',
    focusAreas: ['growth', 'communication'],
    difficulty: 'deeper',
    slug: 'future-vision',
    journeyType: 'workshop',
    durationMinutes: 10,
    steps: [
      {
        dayIndex: 0,
        title: 'Future Vision',
        sparkId: 'spark-11',
      },
    ],
  },
  {
    id: 'devotional-5',
    title: 'Soft Starts, Gentle Words',
    days: 7,
    overview: 'Devotional on gentle communication and conflict de-escalation.',
    focusAreas: ['communication', 'conflict'],
    difficulty: 'light',
    slug: 'soft-starts-gentle-words',
    journeyType: 'devotional',
    durationDays: 7,
    steps: Array.from({ length: 7 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Gentle Communication`,
      sparkId: ['spark-3', 'spark-4', 'spark-12'][i % 3],
    })),
  },
  {
    id: 'devotional-6',
    title: 'Tiny Trust Deposits',
    days: 10,
    overview: 'Daily micro-actions to slowly rebuild trust.',
    focusAreas: ['trust'],
    difficulty: 'deeper',
    slug: 'tiny-trust-deposits',
    journeyType: 'devotional',
    durationDays: 10,
    steps: Array.from({ length: 10 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Trust Building`,
      sparkId: ['spark-9', 'spark-7'][i % 2],
    })),
  },
  {
    id: 'devotional-7',
    title: 'Reconnecting After Distance',
    days: 14,
    overview: 'For couples who travel often or live apart; small daily rituals to feel closer.',
    focusAreas: ['communication', 'intimacy'],
    difficulty: 'light',
    slug: 'reconnecting-after-distance',
    journeyType: 'devotional',
    durationDays: 14,
    steps: Array.from({ length: 14 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Connection`,
      sparkId: ['spark-1', 'spark-3', 'spark-5'][i % 3],
    })),
  },
  {
    id: 'devotional-8',
    title: 'Playful Moments, Daily',
    days: 7,
    overview: 'Simple prompts to add 5 minutes of play into each day.',
    focusAreas: ['play'],
    difficulty: 'light',
    slug: 'playful-moments-daily',
    journeyType: 'devotional',
    durationDays: 7,
    steps: Array.from({ length: 7 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Play`,
      sparkId: ['spark-5', 'spark-6'][i % 2],
    })),
  },
  {
    id: 'devotional-9',
    title: 'Rituals of Comfort',
    days: 12,
    overview: 'Build shared rituals for mornings, evenings, and stressful days.',
    focusAreas: ['growth', 'gratitude'],
    difficulty: 'light',
    slug: 'rituals-of-comfort',
    journeyType: 'devotional',
    durationDays: 12,
    steps: Array.from({ length: 12 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Rituals`,
      sparkId: ['spark-2', 'spark-10', 'spark-1'][i % 3],
    })),
  },
  {
    id: 'devotional-10',
    title: 'Emotional Check-In Practice',
    days: 7,
    overview: 'Daily emotional vocab + feelings check-ins.',
    focusAreas: ['communication', 'boundaries'],
    difficulty: 'light',
    slug: 'emotional-check-in-practice',
    journeyType: 'devotional',
    durationDays: 7,
    steps: Array.from({ length: 7 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Emotional Check-In`,
      sparkId: ['spark-1', 'spark-12'][i % 2],
    })),
  },
  {
    id: 'devotional-11',
    title: 'Curiosity Over Assumption',
    days: 9,
    overview: 'Train the habit of asking better questions instead of mind-reading.',
    focusAreas: ['communication', 'trust'],
    difficulty: 'light',
    slug: 'curiosity-over-assumption',
    journeyType: 'devotional',
    durationDays: 9,
    steps: Array.from({ length: 9 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Curiosity`,
      sparkId: ['spark-3', 'spark-1'][i % 2],
    })),
  },
  {
    id: 'devotional-12',
    title: 'Inner World, Shared',
    days: 8,
    overview: 'Daily reflections where each partner shares one inner thought or fear.',
    focusAreas: ['intimacy', 'growth'],
    difficulty: 'deeper',
    slug: 'inner-world-shared',
    journeyType: 'devotional',
    durationDays: 8,
    steps: Array.from({ length: 8 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Inner World`,
      sparkId: ['spark-3', 'spark-8'][i % 2],
    })),
  },
  {
    id: 'devotional-13',
    title: 'Love in Ordinary Days',
    days: 10,
    overview: 'Notice and savor ordinary, non-Instagram moments.',
    focusAreas: ['gratitude', 'play'],
    difficulty: 'light',
    slug: 'love-in-ordinary-days',
    journeyType: 'devotional',
    durationDays: 10,
    steps: Array.from({ length: 10 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Ordinary Love`,
      sparkId: ['spark-2', 'spark-10'][i % 2],
    })),
  },
  {
    id: 'devotional-14',
    title: 'Boundaries & Belonging',
    days: 7,
    overview: 'Gentle prompts about boundaries, needs, and feeling safe together.',
    focusAreas: ['boundaries', 'conflict'],
    difficulty: 'deeper',
    slug: 'boundaries-and-belonging',
    journeyType: 'devotional',
    durationDays: 7,
    steps: Array.from({ length: 7 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Boundaries`,
      sparkId: ['spark-7', 'spark-4'][i % 2],
    })),
  },
  {
    id: 'devotional-15',
    title: 'Future Us: 30-Day Vision',
    days: 30,
    overview: 'Longer devotional to explore shared goals and future plans.',
    focusAreas: ['growth', 'communication'],
    difficulty: 'deeper',
    slug: 'future-us-30-day-vision',
    journeyType: 'devotional',
    durationDays: 30,
    steps: Array.from({ length: 30 }, (_, i) => ({
      dayIndex: i,
      title: `Day ${i + 1}: Future Vision`,
      sparkId: ['spark-11', 'spark-8', 'spark-3'][i % 3],
    })),
  },
  {
    id: 'workshop-5',
    title: 'Repair After a Tough Talk',
    days: 1,
    overview: 'One-session guide to apologize, validate, and reconnect after a conflict.',
    focusAreas: ['conflict', 'trust'],
    difficulty: 'brave',
    slug: 'repair-after-tough-talk',
    journeyType: 'workshop',
    durationMinutes: 16,
    steps: [
      {
        dayIndex: 0,
        title: 'Repair After Conflict',
        sparkId: 'spark-4',
      },
    ],
  },
  {
    id: 'workshop-6',
    title: 'Design Your Ideal Date Night',
    days: 1,
    overview: 'Co-create a dream date that fits your real life.',
    focusAreas: ['play', 'communication'],
    difficulty: 'light',
    slug: 'design-ideal-date-night',
    journeyType: 'workshop',
    durationMinutes: 12,
    steps: [
      {
        dayIndex: 0,
        title: 'Date Night Planning',
        sparkId: 'spark-6',
      },
    ],
  },
  {
    id: 'workshop-7',
    title: 'Love Map Refresh',
    days: 1,
    overview: 'Guided questions to update what you know about your partner\'s inner world.',
    focusAreas: ['communication', 'intimacy'],
    difficulty: 'light',
    slug: 'love-map-refresh',
    journeyType: 'workshop',
    durationMinutes: 15,
    steps: [
      {
        dayIndex: 0,
        title: 'Love Map Update',
        sparkId: 'spark-3',
      },
    ],
  },
  {
    id: 'workshop-8',
    title: 'Gratitude Letter Lab',
    days: 1,
    overview: 'Turn appreciation into a written letter you can share.',
    focusAreas: ['gratitude'],
    difficulty: 'light',
    slug: 'gratitude-letter-lab',
    journeyType: 'workshop',
    durationMinutes: 10,
    steps: [
      {
        dayIndex: 0,
        title: 'Gratitude Letter',
        sparkId: 'spark-10',
      },
    ],
  },
  {
    id: 'workshop-9',
    title: 'Conflict Styles Snapshot',
    days: 1,
    overview: 'Quickly identify each partner\'s conflict style and choose one upgrade.',
    focusAreas: ['conflict', 'growth'],
    difficulty: 'deeper',
    slug: 'conflict-styles-snapshot',
    journeyType: 'workshop',
    durationMinutes: 14,
    steps: [
      {
        dayIndex: 0,
        title: 'Conflict Styles',
        sparkId: 'spark-4',
      },
    ],
  },
  {
    id: 'workshop-10',
    title: 'Intimacy Check-In',
    days: 1,
    overview: 'One gentle conversation about emotional and physical intimacy needs.',
    focusAreas: ['intimacy'],
    difficulty: 'deeper',
    slug: 'intimacy-check-in',
    journeyType: 'workshop',
    durationMinutes: 18,
    steps: [
      {
        dayIndex: 0,
        title: 'Intimacy Check-In',
        sparkId: 'spark-5',
      },
    ],
  },
  {
    id: 'workshop-11',
    title: 'Family & Home Harmony',
    days: 1,
    overview: 'Talk through chores, roles, and home rhythm in one session.',
    focusAreas: ['boundaries', 'communication'],
    difficulty: 'light',
    slug: 'family-home-harmony',
    journeyType: 'workshop',
    durationMinutes: 15,
    steps: [
      {
        dayIndex: 0,
        title: 'Family & Home',
        sparkId: 'spark-7',
      },
    ],
  },
  {
    id: 'workshop-12',
    title: 'Stress & Support Gameplan',
    days: 1,
    overview: 'Map out how to support each other during stressful weeks.',
    focusAreas: ['communication', 'trust'],
    difficulty: 'light',
    slug: 'stress-support-gameplan',
    journeyType: 'workshop',
    durationMinutes: 12,
    steps: [
      {
        dayIndex: 0,
        title: 'Stress Support',
        sparkId: 'spark-12',
      },
    ],
  },
  {
    id: 'workshop-13',
    title: 'Long Distance Connection Boost',
    days: 1,
    overview: 'Create a weekly rhythm for couples who are apart.',
    focusAreas: ['communication', 'intimacy'],
    difficulty: 'light',
    slug: 'long-distance-connection-boost',
    journeyType: 'workshop',
    durationMinutes: 11,
    steps: [
      {
        dayIndex: 0,
        title: 'Long Distance Connection',
        sparkId: 'spark-1',
      },
    ],
  },
  {
    id: 'workshop-14',
    title: 'Shared Values Spotlight',
    days: 1,
    overview: 'Identify 3–5 core shared values and how they show up in your life.',
    focusAreas: ['growth', 'communication'],
    difficulty: 'deeper',
    slug: 'shared-values-spotlight',
    journeyType: 'workshop',
    durationMinutes: 17,
    steps: [
      {
        dayIndex: 0,
        title: 'Shared Values',
        sparkId: 'spark-8',
      },
    ],
  },
  {
    id: 'workshop-15',
    title: 'Story of a Favorite Memory',
    days: 1,
    overview: 'A guided storytelling session around one important shared memory.',
    focusAreas: ['play', 'gratitude'],
    difficulty: 'light',
    slug: 'story-of-favorite-memory',
    journeyType: 'workshop',
    durationMinutes: 8,
    steps: [
      {
        dayIndex: 0,
        title: 'Favorite Memory',
        sparkId: 'spark-2',
      },
    ],
  },
  {
    id: 'workshop-16',
    title: 'Self-Care & We-Care',
    days: 1,
    overview: 'Balance individual self-care with time together.',
    focusAreas: ['boundaries', 'intimacy'],
    difficulty: 'light',
    slug: 'self-care-we-care',
    journeyType: 'workshop',
    durationMinutes: 9,
    steps: [
      {
        dayIndex: 0,
        title: 'Self-Care Balance',
        sparkId: 'spark-7',
      },
    ],
  },
];

export const ONBOARDING_GOALS = [
  'Improve communication',
  'Rebuild trust',
  'Resolve conflicts better',
  'Increase intimacy',
  'Have more fun together',
  'Support each other\'s growth',
  'Practice daily gratitude',
  'Set healthy boundaries',
];

export const TAGLINE_WORDS = ['Connect', 'Communicate', 'Grow'];

export const SEED_INSPIRATION: InspirationEntry[] = [
  {
    id: 'inspo-1',
    type: 'quote',
    content: 'Love is not about how many days, months, or years you have been together. It is about how much you love each other every single day.',
    author: 'Unknown',
    category: 'Love',
    tags: ['daily', 'connection'],
    mood: 'hopeful',
  },
  {
    id: 'inspo-2',
    type: 'affirmation',
    content: 'I am worthy of a healthy, loving relationship built on trust and respect.',
    category: 'Self-Love',
    tags: ['affirmation', 'self-worth'],
    mood: 'empowered',
  },
  {
    id: 'inspo-3',
    type: 'ritual',
    content: 'Morning gratitude: Before checking your phone, name three things you appreciate about your relationship.',
    category: 'Daily Ritual',
    tags: ['morning', 'gratitude', 'routine'],
    mood: 'grateful',
  },
  {
    id: 'inspo-4',
    type: 'quote',
    content: 'The best thing to hold onto in life is each other.',
    author: 'Audrey Hepburn',
    category: 'Connection',
    tags: ['classic', 'togetherness'],
    mood: 'warm',
  },
  {
    id: 'inspo-5',
    type: 'prompt',
    content: 'What would you do today if you knew it was your partner\'s love language?',
    category: 'Reflection',
    tags: ['love-languages', 'action'],
    mood: 'thoughtful',
  },
  {
    id: 'inspo-6',
    type: 'affirmation',
    content: 'My relationship is a safe space for growth, vulnerability, and joy.',
    category: 'Relationship',
    tags: ['affirmation', 'safety'],
    mood: 'peaceful',
  },
  {
    id: 'inspo-7',
    type: 'ritual',
    content: 'End-of-day connection: Spend 10 minutes talking about your highs and lows without phones.',
    category: 'Evening Ritual',
    tags: ['evening', 'connection', 'presence'],
    mood: 'intimate',
  },
  {
    id: 'inspo-8',
    type: 'quote',
    content: 'To love is nothing. To be loved is something. But to love and be loved, that\'s everything.',
    author: 'Tolis',
    category: 'Love',
    tags: ['mutual', 'deep'],
    mood: 'romantic',
  },
];

export const SEED_GAMES_TURN_BASED: Game[] = [
  {
    id: 'game-1',
    title: "L'Inked",
    description: 'A collaborative storytelling game. Each partner adds one sentence at a time to build a shared story together.',
    type: 'turn-based',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 20,
  },
  {
    id: 'game-2',
    title: 'Echo',
    description: 'A reflective emotional game where each response must "echo" a word from the partner\'s previous sentence.',
    type: 'turn-based',
    category: 'deep',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 15,
  },
  {
    id: 'game-3',
    title: 'Memory Lane',
    description: 'Partners share favorite memories, rank them, and score points based on smiles and forgotten moments.',
    type: 'turn-based',
    category: 'romantic',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 25,
  },
  {
    id: 'game-4',
    title: 'The Level-Up Game',
    description: 'Take turns sharing things you appreciate about each other, moving from light to deeper affirmations.',
    type: 'turn-based',
    category: 'romantic',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 20,
  },
  {
    id: 'game-5',
    title: 'The 36 Questions That Lead to Love',
    description: 'Answer progressively deeper questions proven to build emotional closeness.',
    type: 'turn-based',
    category: 'deep',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 60,
  },
  {
    id: 'game-6',
    title: 'Chess',
    description: 'Play a strategy game together using any preferred chess platform and read each other\'s moves.',
    type: 'turn-based',
    category: 'competitive',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 30,
  },
  {
    id: 'game-7',
    title: 'Words With Friends (Scrabble Style)',
    description: 'A word-building game where you compete while forming clever or romantic phrases through your played words.',
    type: 'turn-based',
    category: 'competitive',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 30,
  },
];

export const SEED_GAMES_COLLABORATIVE: Game[] = [
  {
    id: 'collab-1',
    title: 'Two Truths and a Lie',
    description: 'A playful reveal-and-guess game with optional themed rounds.',
    type: 'collaborative',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 4,
    estTime: 15,
  },
  {
    id: 'collab-2',
    title: 'Truth or Dare — Relationship Remix',
    description: 'A flirty truth-or-dare experience with funny, romantic, and intimate categories.',
    type: 'collaborative',
    category: 'romantic',
    minPlayers: 2,
    maxPlayers: 4,
    estTime: 20,
  },
  {
    id: 'collab-3',
    title: 'Pieces of Us (Integrated Puzzle Game)',
    description: 'A calming couples\' puzzle featuring relationship photos or milestones with memory-unlock prompts.',
    type: 'collaborative',
    category: 'romantic',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 30,
  },
  {
    id: 'collab-4',
    title: 'The Compatibility Challenge',
    description: 'Compare your answers to fun hypothetical scenarios to reveal how aligned you are.',
    type: 'collaborative',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 20,
  },
  {
    id: 'collab-5',
    title: 'Would You Rather — Couples Edition',
    description: 'A humorous and revealing game where each question sparks laughter or values-driven insights.',
    type: 'collaborative',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 4,
    estTime: 15,
  },
  {
    id: 'collab-6',
    title: 'The "Favorites" Game',
    description: 'A fast-paced guessing game about each other\'s favorites—loser owes a favor.',
    type: 'collaborative',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 15,
  },
  {
    id: 'collab-7',
    title: 'Talk Time: "Scenario Swap"',
    description: 'Act out real or imaginary situations and try responding as each other.',
    type: 'collaborative',
    category: 'fun',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 20,
  },
  {
    id: 'collab-8',
    title: 'The "Battle of Opinions" Debate Game',
    description: 'Debate funny or trivial topics with timed rounds—winner chooses the next date night.',
    type: 'collaborative',
    category: 'competitive',
    minPlayers: 2,
    maxPlayers: 2,
    estTime: 20,
  },
];

export const SEED_CHALLENGES: CommunityChallenge[] = [
  {
    id: 'challenge-4',
    title: 'Winter Advent Calendar',
    emoji: '❄️',
    description: 'Celebrate the season with one Winter Wonder each day & share your experience!',
    startDate: '2025-12-01',
    endDate: '2025-12-25',
    participants: 2103,
    category: 'seasonal',
    status: 'active',
  },
  {
    id: 'challenge-1',
    title: '30 Days of Gratitude',
    emoji: '🙏',
    description: 'Share one thing you\'re grateful for about your relationship every day for 30 days.',
    startDate: '2025-01-01',
    endDate: '2025-01-31',
    participants: 1247,
    category: 'romantic',
    status: 'active',
  },
  {
    id: 'challenge-2',
    title: 'Weekly Date Night',
    emoji: '💝',
    description: 'Commit to one intentional date night every week for a month.',
    startDate: '2025-01-15',
    endDate: '2025-02-15',
    participants: 892,
    category: 'romantic',
    status: 'active',
  },
  {
    id: 'challenge-3',
    title: 'Communication Sprint',
    emoji: '💬',
    description: 'Have one deep conversation daily for 7 days using our curated questions.',
    startDate: '2025-02-01',
    endDate: '2025-02-07',
    participants: 0,
    category: 'deep',
    status: 'upcoming',
  },
];
