import { SPACING } from './colors';

export const HEADER_LAYOUT = {
  HEADER_HEIGHT: 36,
  HEADER_BOTTOM_MARGIN: SPACING.xs,
  HEADER_SECTION_BOTTOM_MARGIN: SPACING.xs,
  SUBTITLE_BOTTOM_MARGIN: SPACING.xs,
  MANTRA_TOP_MARGIN: SPACING.sm + 4,
  MANTRA_BOTTOM_MARGIN: SPACING.md,
  DIVIDER_BOTTOM_MARGIN: SPACING.md,
  MANTRA_CONTAINER_BOTTOM_MARGIN: SPACING.xs,
  FIRST_SECTION_HEADER_BOTTOM_MARGIN: SPACING.md,
  FIRST_SECTION_ICON_SIZE: 20,
} as const;

export const HEADER_RIGHT_OFFSET = 16;
export const HEADER_TOP_OFFSET = 8;
export const HEADER_PROFILE_BTN_SIZE = 36;
export const HEADER_PROFILE_ICON_SIZE = 20;
