import { ParqItem, InspoSection, InspoPost } from '@/types';

export function getUserSeededStories(userId: string): InspoPost[] {
  return [
    {
      id: 'post-1',
      sectionId: 'section-date-night',
      title: 'The Picnic Proposal',
      body: 'We went to our favorite park with a basket full of inside jokes: snacks from our first date, a playlist of "our songs," and a handwritten list of my favorite memories with them. It wasn\'t fancy, but it was us.',
      actionSparkText: 'Plan a picnic with items that represent your relationship story',
      actionSparkType: 'prompt',
      tags: ['Budget-Friendly', 'Meaningful', 'Outdoor'],
      source: 'user',
      status: 'approved',
      authorUserId: userId,
      privacy: 'credited',
      isTopStory: false,
      isWeeklyCurated: false,
      likes: 247,
      commentsCount: 18,
      createdAt: '2025-01-01T00:00:00Z',
      updatedAt: '2025-01-01T00:00:00Z',
      hasMedia: false,
    },
    {
      id: 'post-2',
      sectionId: 'section-date-night',
      title: 'Tuesday Night Turn-Down',
      body: 'Date night doesn\'t have to be Saturday. We started doing "Tuesday Turn-Downs"—after work, we change into comfy clothes, light a candle, order takeout, and watch something new together. No phones allowed.',
      actionSparkText: 'Pick an unexpected weeknight for your next date',
      actionSparkType: 'other',
      tags: ['Weeknight', 'Low-Effort', 'Cozy'],
      source: 'user',
      status: 'approved',
      authorUserId: userId,
      privacy: 'credited',
      isTopStory: false,
      isWeeklyCurated: false,
      likes: 189,
      commentsCount: 12,
      createdAt: '2025-01-02T00:00:00Z',
      updatedAt: '2025-01-02T00:00:00Z',
      hasMedia: false,
    },
  ];
}

export function getStoryDisplayAuthor(
  post: { authorUserId?: string; privacy?: 'credited' | 'anonymous'; authorDisplayName?: string },
  currentUser: { id: string; username?: string; name?: string } | null
): string {
  if (post.privacy === 'anonymous') {
    return 'Anonymous';
  }
  
  if (post.authorUserId && currentUser && post.authorUserId === currentUser.id) {
    const username = currentUser.username || currentUser.name?.toLowerCase().replace(/\s+/g, '') || 'sparkduser';
    return `@${username}`;
  }
  
  if (post.authorDisplayName) {
    return post.authorDisplayName;
  }
  
  return 'Anonymous';
}

export const SEED_PARQ_ITEMS: ParqItem[] = [
  {
    id: 'parq-prompt-1',
    type: 'prompt',
    text: 'If you could only ask me one question today that would help you understand me better, what would it be?',
    themeTags: ['Communication', 'Curiosity', 'Deep Talk'],
    toneTag: 'Thoughtful',
    source: 'curated',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'parq-prompt-2',
    type: 'prompt',
    text: 'What\'s one thing about me you wish I knew you appreciated more?',
    themeTags: ['Gratitude', 'Acknowledgment'],
    toneTag: 'Warm',
    source: 'curated',
    createdAt: '2025-01-02T00:00:00Z',
  },
  {
    id: 'parq-prompt-3',
    type: 'prompt',
    text: 'When was the last time you felt truly seen by me? What made that moment special?',
    themeTags: ['Intimacy', 'Connection', 'Reflection'],
    toneTag: 'Vulnerable',
    source: 'curated',
    createdAt: '2025-01-03T00:00:00Z',
  },
  {
    id: 'parq-affirmation-1',
    type: 'affirmation',
    text: 'I am worthy of a love that feels safe, exciting, and real.',
    themeTags: ['Self-Love', 'Boundaries', 'Worth'],
    toneTag: 'Empowered',
    source: 'curated',
    createdAt: '2025-01-04T00:00:00Z',
  },
  {
    id: 'parq-affirmation-2',
    type: 'affirmation',
    text: 'We are growing together, not growing apart. Every conversation is a step forward.',
    themeTags: ['Growth', 'Partnership', 'Progress'],
    toneTag: 'Hopeful',
    source: 'curated',
    createdAt: '2025-01-05T00:00:00Z',
  },
  {
    id: 'parq-affirmation-3',
    type: 'affirmation',
    text: 'I choose to show up fully, even when it\'s uncomfortable. This is how love deepens.',
    themeTags: ['Courage', 'Vulnerability', 'Presence'],
    toneTag: 'Brave',
    source: 'curated',
    createdAt: '2025-01-06T00:00:00Z',
  },
  {
    id: 'parq-ritual-1',
    type: 'ritual',
    text: 'Daily Reset: At the end of each day, hold hands for 30 seconds and share one thing that made you smile.',
    themeTags: ['Daily', 'Gratitude', 'Connection'],
    toneTag: 'Grounded',
    source: 'curated',
    createdAt: '2025-01-07T00:00:00Z',
  },
  {
    id: 'parq-ritual-2',
    type: 'ritual',
    text: 'Sunday Reset: Start each week by writing one thing you appreciate about your partner and leaving it somewhere they\'ll find it.',
    themeTags: ['Weekly', 'Appreciation', 'Surprise'],
    toneTag: 'Playful',
    source: 'curated',
    createdAt: '2025-01-08T00:00:00Z',
  },
  {
    id: 'parq-ritual-3',
    type: 'ritual',
    text: 'Monthly Check-In: Set aside 30 minutes to answer: "What\'s working? What needs attention? What do we want more of?"',
    themeTags: ['Monthly', 'Reflection', 'Alignment'],
    toneTag: 'Intentional',
    source: 'curated',
    createdAt: '2025-01-09T00:00:00Z',
  },
  {
    id: 'parq-quote-1',
    type: 'quote',
    text: 'Love is not something you find. Love is something you build.',
    themeTags: ['Love', 'Partnership', 'Effort'],
    toneTag: 'Inspiring',
    source: 'curated',
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    id: 'parq-quote-2',
    type: 'quote',
    text: 'The best relationships are the ones where you can be weird together.',
    themeTags: ['Playfulness', 'Authenticity', 'Joy'],
    toneTag: 'Lighthearted',
    source: 'curated',
    createdAt: '2025-01-11T00:00:00Z',
  },
  {
    id: 'parq-quote-3',
    type: 'quote',
    text: 'A strong relationship requires choosing to love each other, even in those moments when you struggle to like each other.',
    themeTags: ['Commitment', 'Resilience', 'Choice'],
    toneTag: 'Honest',
    source: 'curated',
    createdAt: '2025-01-12T00:00:00Z',
  },
];

export const INSPO_SECTIONS: InspoSection[] = [
  {
    id: 'section-top-stories',
    slug: 'top-stories',
    label: 'Top Stories',
    emoji: '🔥',
    description: 'Standout stories and ideas loved by the Spark\'d community.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 1,
  },
  {
    id: 'section-weekly-curated',
    slug: 'weekly-curated',
    label: 'Weekly Curated Ideas',
    emoji: '👐',
    description: 'Handpicked prompts, gestures, and rituals chosen for this week.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 2,
  },
  {
    id: 'section-holiday-magic',
    slug: 'holiday-magic',
    label: 'Holiday Magic',
    emoji: '☃️',
    description: 'Festive ideas and traditions to make the holidays more magical together.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 3,
  },
  {
    id: 'section-date-night',
    slug: 'date-night',
    label: 'Date Night',
    emoji: '🍷',
    description: 'Ideas to plan intentional, memorable date nights together.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 4,
  },
  {
    id: 'section-recipes',
    slug: 'recipes',
    label: 'Recipes from the Heart',
    emoji: '🍝',
    description: 'A dish to prepare together or for your partner tonight — romantic meals, cozy comfort food, or sweet desserts.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 5,
  },
  {
    id: 'section-gift-giving',
    slug: 'gift-giving',
    label: 'The Perfect Gift',
    emoji: '🎁',
    description: 'Thoughtful gift ideas that feel personal and meaningful.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 6,
  },
  {
    id: 'section-celebrate',
    slug: 'celebrate',
    label: 'Let\'s Celebrate',
    emoji: '🎈',
    description: 'Festive ideas to celebrate your partner and mark special moments in meaningful ways.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 7,
  },
  {
    id: 'section-making-official',
    slug: 'making-official',
    label: 'Making It Official',
    emoji: '💍',
    description: 'Moments, scripts, and ideas for defining the relationship or taking the next step.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 8,
  },
  {
    id: 'section-party-of-2',
    slug: 'party-of-2',
    label: 'Party of 2',
    emoji: '🎊',
    description: 'Fun things couples can do without leaving the house — cozy, playful, or creative stay-in date ideas.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 9,
  },
  {
    id: 'section-meaningful-gestures',
    slug: 'meaningful-gestures',
    label: 'Meaningful Gestures',
    emoji: '☕️',
    description: 'Small, everyday gestures that make your partner feel seen and cared for.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 10,
  },
  {
    id: 'section-swole-mates',
    slug: 'swole-mates',
    label: 'Swole-Mates',
    emoji: '💪',
    description: 'Creative, fun, and energizing ways for couples to shake up their shared fitness journey — from movement-based bonding to teamwork-driven wellness challenges.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 11,
  },
  {
    id: 'section-diy-projects',
    slug: 'diy-projects',
    label: 'DIY Projects',
    emoji: '⚒️',
    description: 'Home décor, crafts, and build-together projects that turn creativity into connection.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 12,
  },
  {
    id: 'section-long-distance',
    slug: 'long-distance',
    label: 'Long Distance',
    emoji: '🌎',
    description: 'Connection rituals and gestures for couples loving each other from afar.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 13,
  },
  {
    id: 'section-romantic-getaways',
    slug: 'romantic-getaways',
    label: 'Romantic Getaways',
    emoji: '✈️',
    description: 'Trips and escapes, from weekend getaways to dream destinations.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 14,
  },
  {
    id: 'section-self-care',
    slug: 'self-care',
    label: 'Self-Care',
    emoji: '🧘‍♀️',
    description: 'Personal rituals for rest, reset, and renewal.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 15,
  },
  {
    id: 'section-just-because',
    slug: 'just-because',
    label: 'Just Because',
    emoji: '💐',
    description: 'Spontaneous, unexpected expressions of love—no special occasion required.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 16,
  },
  {
    id: 'section-party-of-1',
    slug: 'party-of-1',
    label: 'Party of 1',
    emoji: '🎉',
    description: 'Celebrating yourself and the joy of solo experiences.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 17,
  },
  {
    id: 'section-tell-story',
    slug: 'tell-story',
    label: 'Tell Your Story',
    emoji: '💌',
    description: 'Share your own real-life love story or a chapter of your journey.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 18,
  },
  {
    id: 'section-sweet-valentines',
    slug: 'sweet-valentines',
    label: 'Sweet Valentines',
    emoji: '💝',
    description: 'Romantic ideas and heartfelt gestures for Valentine\'s Day and beyond.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 0,
  },
  {
    id: 'section-animated-series',
    slug: 'animated-series',
    label: 'Animated Stories',
    emoji: '🎞️',
    description: 'Animated relationship stories and lessons to watch together.',
    isComingSoon: true,
    isPremium: false,
    sortOrder: 20,
  },
  {
    id: 'section-ask-sparky',
    slug: 'ask-sparky',
    label: 'Ask Sparky!',
    emoji: '🐶',
    description: 'Get personalized relationship advice and guidance from our AI companion.',
    isComingSoon: true,
    isPremium: false,
    sortOrder: 21,
  },
  {
    id: 'section-parqs',
    slug: 'parqs',
    label: 'PARQs',
    emoji: '💬',
    description: 'Saved prompts, affirmations, rituals, and quotes from the PARQ section.',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 22,
  },
];

export const SEED_INSPO_POSTS: InspoPost[] = [

  {
    id: 'post-3',
    sectionId: 'section-gift-giving',
    title: 'QR Code Love Notes',
    body: 'For their birthday, I created QR codes that linked to voice memos, photos, and playlists. I hid them around the house with clues. It took them all day to find them all, and they said it was the best gift they\'ve ever gotten.',
    actionSparkText: 'Create a digital scavenger hunt with personal messages',
    actionSparkType: 'prompt',
    tags: ['Creative', 'Tech-Savvy', 'Birthday', 'Anniversary'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: false,
    likes: 412,
    commentsCount: 34,
    createdAt: '2025-01-03T00:00:00Z',
    updatedAt: '2025-01-03T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/31895335/pexels-photo-31895335.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/31895335/pexels-photo-31895335.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'post-4',
    sectionId: 'section-gift-giving',
    title: 'The "Open When" Letters',
    body: 'I wrote 12 letters labeled "Open when you\'re sad," "Open when you miss me," "Open when you need a laugh," etc. They keep them in a box and say it\'s like having me there even when I\'m not.',
    actionSparkText: 'Write a set of "Open When" letters for your partner',
    actionSparkType: 'prompt',
    tags: ['Thoughtful', 'Long-Distance', 'Emotional Support'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-2',
    authorDisplayName: '@jakelovesnotes',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 356,
    commentsCount: 28,
    createdAt: '2025-01-04T00:00:00Z',
    updatedAt: '2025-01-04T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/8716073/pexels-photo-8716073.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/8716073/pexels-photo-8716073.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  {
    id: 'post-5',
    sectionId: 'section-making-official',
    title: 'The Fortune Cookie Ask',
    body: 'We were at our favorite Chinese restaurant, and I slipped a custom fortune cookie into the waiter\'s hand. When dessert came, their fortune read: "Will you be my partner... officially?" They laughed, then cried, then said yes.',
    actionSparkText: 'Plan a creative way to ask "the question" in a meaningful setting',
    actionSparkType: 'prompt',
    tags: ['Creative', 'Public', 'Memorable'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: false,
    likes: 523,
    commentsCount: 41,
    createdAt: '2025-01-05T00:00:00Z',
    updatedAt: '2025-01-05T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/6691736/pexels-photo-6691736.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/6691736/pexels-photo-6691736.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'post-6',
    sectionId: 'section-meaningful-gestures',
    title: 'The Morning Coffee Ritual',
    body: 'Every morning, I wake up 10 minutes early to make their coffee exactly how they like it. It\'s small, but they say it sets the tone for their entire day. Consistency > grand gestures.',
    actionSparkText: 'Commit to one small daily act of service for a week',
    actionSparkType: 'ritual',
    tags: ['Daily', 'Morning', 'Routine', 'Thoughtful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-3',
    authorDisplayName: '@morningperson_',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 298,
    commentsCount: 22,
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-06T00:00:00Z',
    weeklyCuratedAt: '2025-01-06T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/5722872/pexels-photo-5722872.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/5722872/pexels-photo-5722872.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 3,
  },
  {
    id: 'post-7',
    sectionId: 'section-romantic-getaways',
    title: 'The Surprise Staycation',
    body: 'I booked a hotel in our own city, packed their bag in secret, and told them we were "going somewhere" after work. We spent the weekend exploring our city like tourists: no chores, no errands, just us.',
    actionSparkText: 'Plan a surprise staycation in your own city',
    actionSparkType: 'prompt',
    tags: ['Surprise', 'Weekend', 'Local', 'Adventure'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 445,
    commentsCount: 31,
    createdAt: '2025-01-07T00:00:00Z',
    updatedAt: '2025-01-07T00:00:00Z',
    weeklyCuratedAt: '2025-01-07T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/3575144/pexels-photo-3575144.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/3575144/pexels-photo-3575144.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  {
    id: 'post-8',
    sectionId: 'section-just-because',
    title: 'The Random Dance Party',
    body: 'I put on their favorite song in the middle of a random Tuesday and said, "Dance with me. Right now." We danced in the kitchen for 3 minutes. It reset the entire week.',
    actionSparkText: 'Initiate a spontaneous 3-minute dance party',
    actionSparkType: 'prompt',
    tags: ['Spontaneous', 'Playful', 'Quick', 'Joy'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-4',
    authorDisplayName: '@danceitout',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 381,
    commentsCount: 27,
    createdAt: '2025-01-08T00:00:00Z',
    updatedAt: '2025-01-08T00:00:00Z',
    weeklyCuratedAt: '2025-01-08T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/4554393/pexels-photo-4554393.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/4554393/pexels-photo-4554393.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  {
    id: 'post-9',
    sectionId: 'section-parqs',
    title: 'Using Prompts for Deeper Connection',
    body: 'We started using Spark\'d prompts during dinner instead of scrolling our phones. One question led to a 2-hour conversation about dreams we\'ve never shared. It reminded us why we started dating in the first place.',
    actionSparkText: 'What\'s one dream you have that you\'ve never told me about?',
    actionSparkType: 'prompt',
    tags: ['Communication', 'Deep Talk', 'Dinner', 'Connection'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: false,
    likes: 612,
    commentsCount: 48,
    createdAt: '2025-01-09T00:00:00Z',
    updatedAt: '2025-01-09T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/5718125/pexels-photo-5718125.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/5718125/pexels-photo-5718125.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  {
    id: 'post-10',
    sectionId: 'section-holiday-magic',
    title: 'The Yearly Time Capsule',
    body: 'Every New Year\'s Eve, we fill a box with: a letter to each other, a printed photo, a list of goals, and a small object that represents the year. We open last year\'s box and read everything together. It\'s become our favorite tradition.',
    actionSparkText: 'Start a yearly time capsule tradition',
    actionSparkType: 'ritual',
    tags: ['Annual', 'Tradition', 'Reflection', 'Meaningful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-5',
    authorDisplayName: '@newyearnewtraditions',
    isTopStory: true,
    isWeeklyCurated: false,
    likes: 789,
    commentsCount: 56,
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=400&h=400&fit=crop',
    mediaUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800',
  },
  {
    id: 'post-11',
    sectionId: 'section-recipes',
    title: 'Midnight Chocolate Fondue',
    body: 'We made chocolate fondue at 11pm on a random weeknight. Strawberries, marshmallows, pretzels—the whole setup. We sat on the kitchen floor with candles and laughed like kids. Pure joy.',
    actionSparkText: 'Make a simple dessert together tonight',
    actionSparkType: 'prompt',
    tags: ['Dessert', 'Spontaneous', 'Romantic', 'Easy'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-6',
    authorDisplayName: '@sweettoothcouple',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 334,
    commentsCount: 19,
    createdAt: '2025-01-11T00:00:00Z',
    updatedAt: '2025-01-11T00:00:00Z',
    recipeIngredients: '– 12 oz dark or milk chocolate chips\n– 1 cup heavy cream\n– 1 tsp vanilla extract\n– Fresh strawberries\n– Marshmallows\n– Pretzels\n– Banana slices (optional)',
    recipeSteps: '1. Heat heavy cream in a saucepan over medium heat until it just starts to simmer\n2. Remove from heat and add chocolate chips\n3. Let sit for 2 minutes, then stir until smooth\n4. Add vanilla extract and stir\n5. Transfer to a fondue pot or serving bowl\n6. Arrange dippers on a plate and enjoy!',
  },
  {
    id: 'post-12',
    sectionId: 'section-recipes',
    title: 'Sunday Pasta Ritual',
    body: 'Every Sunday, we make fresh pasta from scratch together. One of us rolls, the other cuts. We play Italian music and drink wine. It takes 2 hours but it\'s our favorite tradition.',
    actionSparkText: 'Pick one recipe to cook together from start to finish',
    actionSparkType: 'prompt',
    tags: ['Sunday', 'Tradition', 'Italian', 'Quality Time'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 521,
    commentsCount: 38,
    createdAt: '2025-01-12T00:00:00Z',
    updatedAt: '2025-01-12T00:00:00Z',
    recipeIngredients: '– 2 cups all-purpose flour\n– 3 large eggs\n– 1/2 tsp salt\n– 1 tbsp olive oil\n– Extra flour for dusting',
    recipeSteps: '1. Make a mound with flour on a clean surface, create a well in the center\n2. Crack eggs into the well, add salt and olive oil\n3. Using a fork, gradually incorporate flour from the edges\n4. Knead dough for 8-10 minutes until smooth and elastic\n5. Wrap in plastic and rest for 30 minutes\n6. Roll out dough to desired thickness (use pasta machine if available)\n7. Cut into your preferred pasta shape\n8. Cook in salted boiling water for 2-4 minutes\n9. Serve with your favorite sauce',
  },
  {
    id: 'post-13',
    sectionId: 'section-celebrate',
    title: 'The Promotion Toast',
    body: 'When they got promoted, I decorated the living room with their favorite snacks, put on their hype playlist, and gave a dramatic toast with champagne. We danced around celebrating them for 20 minutes straight.',
    actionSparkText: 'Celebrate your partner\'s next win with a surprise toast',
    actionSparkType: 'prompt',
    tags: ['Career', 'Celebration', 'Support', 'Champagne'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-7',
    authorDisplayName: '@cheerleaderpartner',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 412,
    commentsCount: 24,
    createdAt: '2025-01-13T00:00:00Z',
    updatedAt: '2025-01-13T00:00:00Z',
  },
  {
    id: 'post-14',
    sectionId: 'section-celebrate',
    title: 'Half-Birthday Surprise',
    body: 'Six months after their birthday, I surprised them with a "half-birthday" celebration: half a cake, half-sized presents, and a card that said "You deserve to be celebrated twice a year." They ugly-cried.',
    actionSparkText: 'Mark a random milestone just to make them feel special',
    actionSparkType: 'prompt',
    tags: ['Birthday', 'Creative', 'Surprise', 'Thoughtful'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: false,
    likes: 678,
    commentsCount: 45,
    createdAt: '2025-01-14T00:00:00Z',
    updatedAt: '2025-01-14T00:00:00Z',
  },
  {
    id: 'post-15',
    sectionId: 'section-party-of-2',
    title: 'Living Room Fort Night',
    body: 'We built a blanket fort with string lights, pillows, and snacks. We watched our favorite movie inside and didn\'t leave the fort for 3 hours. Best Friday night in months.',
    actionSparkText: 'Build a blanket fort and have a cozy movie night inside',
    actionSparkType: 'prompt',
    tags: ['Cozy', 'Playful', 'Movie Night', 'Indoor'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-8',
    authorDisplayName: '@blanketfortlovers',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 445,
    commentsCount: 31,
    createdAt: '2025-01-15T00:00:00Z',
    updatedAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'post-16',
    sectionId: 'section-party-of-2',
    title: 'At-Home Trivia Tournament',
    body: 'We found trivia questions online and turned it into a full competition with scoreboards, prizes, and trash talk. Loser had to make breakfast. It got surprisingly intense and hilarious.',
    actionSparkText: 'Host a mini game night with just the two of you',
    actionSparkType: 'prompt',
    tags: ['Games', 'Competitive', 'Fun', 'Quality Time'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 389,
    commentsCount: 28,
    createdAt: '2025-01-16T00:00:00Z',
    updatedAt: '2025-01-16T00:00:00Z',
  },
  {
    id: 'post-17',
    sectionId: 'section-diy-projects',
    title: 'The Photo Wall Project',
    body: 'We spent a Saturday afternoon printing our favorite photos and arranging them into a gallery wall above our bed. Every time we look at it, we remember why we love our life together.',
    actionSparkText: 'Create a photo wall or memory board together',
    actionSparkType: 'prompt',
    tags: ['DIY', 'Photos', 'Memories', 'Decor'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-9',
    authorDisplayName: '@memorymakers',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 512,
    commentsCount: 34,
    createdAt: '2025-01-17T00:00:00Z',
    updatedAt: '2025-01-17T00:00:00Z',
  },
  {
    id: 'post-18',
    sectionId: 'section-diy-projects',
    title: 'Handmade Candle Date',
    body: 'We bought a candle-making kit and spent the afternoon creating custom scents for each other. Mine smells like vanilla and coffee (his favorites), his smells like lavender and citrus (mine). We light them every week.',
    actionSparkText: 'Make something together: candles, art, or a small craft project',
    actionSparkType: 'prompt',
    tags: ['Crafts', 'Handmade', 'Gifts', 'Creative'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 467,
    commentsCount: 29,
    createdAt: '2025-01-18T00:00:00Z',
    updatedAt: '2025-01-18T00:00:00Z',
  },
  {
    id: 'post-19',
    sectionId: 'section-swole-mates',
    title: 'The Sunrise Sweat Pact',
    body: 'We challenged ourselves to start each day with a 10–15 minute movement ritual — stretching, yoga flows, or light cardio. It became our favorite grounding moment before the world wakes up, leaving us feeling connected, energized, and proud of our consistency.',
    actionSparkText: 'Create a morning movement ritual together for one week',
    actionSparkType: 'ritual',
    tags: ['Morning', 'Fitness', 'Routine', 'Wellness'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 327,
    commentsCount: 21,
    createdAt: '2025-01-19T00:00:00Z',
    updatedAt: '2025-01-19T00:00:00Z',
  },
  {
    id: 'post-20',
    sectionId: 'section-swole-mates',
    title: 'Spot Me, Babe',
    body: 'We turned our gym sessions into mini team challenges: matching rep counts, trading off exercises, and cheering each other on. It made the gym way more fun and helped us push each other past our limits — in the best way.',
    actionSparkText: 'Turn your next workout into a partner challenge',
    actionSparkType: 'prompt',
    tags: ['Gym', 'Challenge', 'Support', 'Teamwork'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-10',
    authorDisplayName: '@fitcouple',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 289,
    commentsCount: 17,
    createdAt: '2025-01-20T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
  },
  {
    id: 'post-21',
    sectionId: 'section-self-care',
    title: 'My Sunday Reset Ritual',
    body: 'Laundry, a long shower, skincare, journaling, and an early bedtime.',
    actionSparkText: 'Design your own Sunday reset routine this week',
    actionSparkType: 'ritual',
    tags: ['Self-Care', 'Sunday', 'Routine', 'Reset'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 156,
    commentsCount: 14,
    createdAt: '2025-01-21T00:00:00Z',
    updatedAt: '2025-01-21T00:00:00Z',
  },
  {
    id: 'post-22',
    sectionId: 'section-self-care',
    title: 'Doing Nothing on Purpose',
    body: 'A day with no plans, no guilt — stretching, tea, and silence.',
    actionSparkText: 'Schedule an intentional "nothing" day this month',
    actionSparkType: 'prompt',
    tags: ['Rest', 'Intentional', 'Silence', 'Peace'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 203,
    commentsCount: 19,
    createdAt: '2025-01-22T00:00:00Z',
    updatedAt: '2025-01-22T00:00:00Z',
  },
  {
    id: 'post-23',
    sectionId: 'section-self-care',
    title: 'Mental Health Walk',
    body: 'Headphones in, phone on airplane mode, walking until my thoughts settle.',
    actionSparkText: 'Take a 20-minute walk with no distractions today',
    actionSparkType: 'prompt',
    tags: ['Walking', 'Mental Health', 'Movement', 'Mindfulness'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 178,
    commentsCount: 16,
    createdAt: '2025-01-23T00:00:00Z',
    updatedAt: '2025-01-23T00:00:00Z',
  },
  {
    id: 'post-24',
    sectionId: 'section-party-of-1',
    title: 'Dinner for One, Table for Confidence',
    body: 'Dressed up, sat at the bar, ordered wine, enjoyed every minute.',
    actionSparkText: 'Take yourself on a solo dinner date this week',
    actionSparkType: 'prompt',
    tags: ['Solo Date', 'Confidence', 'Restaurant', 'Self-Love'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 234,
    commentsCount: 21,
    createdAt: '2025-01-24T00:00:00Z',
    updatedAt: '2025-01-24T00:00:00Z',
  },
  {
    id: 'post-25',
    sectionId: 'section-party-of-1',
    title: 'Getting Ready With No Destination',
    body: 'Music on, mirror moment, remembering how good it feels to feel good.',
    actionSparkText: 'Spend an hour getting ready just for yourself',
    actionSparkType: 'prompt',
    tags: ['Self-Care', 'Getting Ready', 'Music', 'Joy'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 189,
    commentsCount: 15,
    createdAt: '2025-01-25T00:00:00Z',
    updatedAt: '2025-01-25T00:00:00Z',
  },
  {
    id: 'post-26',
    sectionId: 'section-party-of-1',
    title: 'Coffee, a Book, and People Watching',
    body: 'No rush, no distractions — just being present.',
    actionSparkText: 'Spend an hour at a café with just yourself and a book',
    actionSparkType: 'prompt',
    tags: ['Coffee', 'Reading', 'Solo Time', 'Present'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 167,
    commentsCount: 12,
    createdAt: '2025-01-26T00:00:00Z',
    updatedAt: '2025-01-26T00:00:00Z',
  },
  {
    id: 'post-27',
    sectionId: 'section-self-care',
    title: 'Write a Letter You\'ll Never Send',
    body: 'A reflection exercise to release thoughts and emotions.',
    actionSparkText: 'Write a letter to someone (or yourself) that you\'ll never send',
    actionSparkType: 'prompt',
    tags: ['Writing', 'Reflection', 'Release', 'Emotional'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 312,
    commentsCount: 27,
    createdAt: '2025-01-27T00:00:00Z',
    updatedAt: '2025-01-27T00:00:00Z',
  },
  {
    id: 'post-28',
    sectionId: 'section-date-night',
    title: 'Plan a Midweek Mini-Date',
    body: 'No phones. No rush. Just presence.',
    actionSparkText: 'Schedule a 30-minute quality time moment this Wednesday',
    actionSparkType: 'prompt',
    tags: ['Midweek', 'Date', 'Presence', 'Connection'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 267,
    commentsCount: 23,
    createdAt: '2025-01-28T00:00:00Z',
    updatedAt: '2025-01-28T00:00:00Z',
  },
  {
    id: 'post-29',
    sectionId: 'section-party-of-1',
    title: 'Solo Confidence Challenge',
    body: 'Go somewhere alone you\'ve been putting off.',
    actionSparkText: 'Pick one place you\'ve wanted to go and go there solo this week',
    actionSparkType: 'prompt',
    tags: ['Solo', 'Challenge', 'Confidence', 'Growth'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 289,
    commentsCount: 25,
    createdAt: '2025-01-29T00:00:00Z',
    updatedAt: '2025-01-29T00:00:00Z',
  },
  {
    id: 'post-30',
    sectionId: 'section-self-care',
    title: 'Create an Evening Wind-Down Ritual',
    body: 'Design a nightly routine that signals rest.',
    actionSparkText: 'Experiment with a new evening routine for 3 nights this week',
    actionSparkType: 'ritual',
    tags: ['Evening', 'Ritual', 'Rest', 'Sleep'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 223,
    commentsCount: 18,
    createdAt: '2025-01-30T00:00:00Z',
    updatedAt: '2025-01-30T00:00:00Z',
  },
  {
    id: 'post-31',
    sectionId: 'section-holiday-magic',
    title: 'Hot Cocoa Bar Tradition',
    body: 'We set up a hot cocoa bar with marshmallows, whipped cream, peppermint sticks, and caramel drizzle. We made it a nightly ritual during the winter months—cozy blankets, holiday movies, and the best conversations.',
    actionSparkText: 'Create a cozy hot cocoa bar and make it a nightly ritual',
    actionSparkType: 'ritual',
    tags: ['Winter', 'Tradition', 'Cozy', 'Holiday'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 345,
    commentsCount: 29,
    createdAt: '2025-01-31T00:00:00Z',
    updatedAt: '2025-01-31T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/5464634/pexels-photo-5464634.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/5464634/pexels-photo-5464634.jpeg?auto=compress&cs=tinysrgb&w=800',
    thumbnailRank: 1,
  },
  {
    id: 'post-32',
    sectionId: 'section-holiday-magic',
    title: 'Winter Lights Walk',
    body: 'Every December, we bundle up and walk through neighborhoods looking at holiday lights. We rate each house, sip warm drinks from thermoses, and make up stories about the families inside. It\'s become our favorite tradition.',
    actionSparkText: 'Plan an evening walk to see holiday lights together',
    actionSparkType: 'prompt',
    tags: ['Winter', 'Walking', 'Holiday Lights', 'Adventure'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-11',
    authorDisplayName: '@winterwalkers',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 412,
    commentsCount: 33,
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: '2025-02-01T00:00:00Z',
    weeklyCuratedAt: '2025-02-01T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/6648807/pexels-photo-6648807.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/6648807/pexels-photo-6648807.jpeg?auto=compress&cs=tinysrgb&w=800',
    thumbnailRank: 2,
  },
  {
    id: 'post-33',
    sectionId: 'section-holiday-magic',
    title: 'Snowed-In Date Night',
    body: 'When a blizzard kept us inside, we made it magical: built a blanket fort, baked cookies from scratch, played board games by candlelight, and pretended we were in a snow globe. Best storm ever.',
    actionSparkText: 'Turn a snowy day into an indoor adventure',
    actionSparkType: 'prompt',
    tags: ['Snow', 'Indoor', 'Spontaneous', 'Cozy'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 521,
    commentsCount: 38,
    createdAt: '2025-02-02T00:00:00Z',
    updatedAt: '2025-02-02T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/13613342/pexels-photo-13613342.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/13613342/pexels-photo-13613342.jpeg?auto=compress&cs=tinysrgb&w=800',
    thumbnailRank: 3,
  },
  {
    id: 'post-34',
    sectionId: 'section-long-distance',
    title: 'Netflix Party Every Friday',
    body: 'We use screen share to watch shows together every Friday night, even though we\'re in different time zones. We text reactions, pause to laugh together, and it makes the distance feel smaller.',
    actionSparkText: 'Schedule a weekly virtual movie night with your long-distance partner',
    actionSparkType: 'ritual',
    tags: ['Long-Distance', 'Virtual Date', 'Routine', 'Movies'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-12',
    authorDisplayName: '@distancebutclose',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 487,
    commentsCount: 41,
    createdAt: '2025-02-03T00:00:00Z',
    updatedAt: '2025-02-03T00:00:00Z',
  },
  {
    id: 'post-35',
    sectionId: 'section-long-distance',
    title: 'The Shared Playlist',
    body: 'We created a playlist where we each add songs that remind us of each other or our relationship. We update it weekly and listen to it when we miss each other. It\'s like a musical conversation.',
    actionSparkText: 'Create a shared playlist and add to it weekly',
    actionSparkType: 'prompt',
    tags: ['Long-Distance', 'Music', 'Connection', 'Creative'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 398,
    commentsCount: 27,
    createdAt: '2025-02-04T00:00:00Z',
    updatedAt: '2025-02-04T00:00:00Z',
  },
  {
    id: 'post-36',
    sectionId: 'section-long-distance',
    title: 'Countdown Calendar',
    body: 'We made a shared digital countdown to our next visit. Every day, one of us sends a photo or voice note. When the countdown hits zero, we have a collection of moments that got us through the wait.',
    actionSparkText: 'Start a countdown calendar with daily check-ins',
    actionSparkType: 'prompt',
    tags: ['Long-Distance', 'Countdown', 'Photos', 'Anticipation'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-13',
    authorDisplayName: '@countingthedays',
    isTopStory: true,
    isWeeklyCurated: true,
    likes: 534,
    commentsCount: 44,
    createdAt: '2025-02-05T00:00:00Z',
    updatedAt: '2025-02-05T00:00:00Z',
  },
  {
    id: 'post-37',
    sectionId: 'section-making-official',
    title: 'The Sunset Proposal',
    body: 'I took them to the beach where we had our first deep conversation. As the sun set, I pulled out a handwritten letter reading all the reasons I wanted to make it official. They said yes before I even finished reading.',
    actionSparkText: 'Return to a meaningful location and express your commitment',
    actionSparkType: 'prompt',
    tags: ['Proposal', 'Beach', 'Romantic', 'Meaningful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-14',
    authorDisplayName: '@beachproposal',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 467,
    commentsCount: 36,
    createdAt: '2025-02-06T00:00:00Z',
    updatedAt: '2025-02-06T00:00:00Z',
  },
  {
    id: 'post-38',
    sectionId: 'section-making-official',
    title: 'The Playlist Proposal',
    body: 'I created a playlist titled "Will you be mine?" with songs that spelled out my feelings. The last track was a voice recording of me asking them to be official. They called me crying—happy tears.',
    actionSparkText: 'Create a meaningful playlist that asks "the question"',
    actionSparkType: 'prompt',
    tags: ['Creative', 'Music', 'Voice Note', 'Emotional'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: true,
    likes: 589,
    commentsCount: 47,
    createdAt: '2025-02-07T00:00:00Z',
    updatedAt: '2025-02-07T00:00:00Z',
  },
  {
    id: 'post-39',
    sectionId: 'section-meaningful-gestures',
    title: 'Fill Their Tank on Busy Mornings',
    body: 'Whenever they have an early meeting or stressful day, I wake up first and fill their car with gas. They always notice, and it\'s my way of saying "I\'ve got you."',
    actionSparkText: 'Do one small task to ease your partner\'s busy day',
    actionSparkType: 'prompt',
    tags: ['Acts of Service', 'Morning', 'Support', 'Thoughtful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-15',
    authorDisplayName: '@gasstation_love',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 312,
    commentsCount: 22,
    createdAt: '2025-02-08T00:00:00Z',
    updatedAt: '2025-02-08T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/3812750/pexels-photo-3812750.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/3812750/pexels-photo-3812750.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 1,
  },
  {
    id: 'post-40',
    sectionId: 'section-meaningful-gestures',
    title: 'The Sticky Note Trail',
    body: 'On days when they\'re stressed, I leave sticky notes around the house with little affirmations and reminders of why I love them. On the mirror, in their lunch, on the steering wheel. Small words, big impact.',
    actionSparkText: 'Leave surprise sticky notes with affirmations around the house',
    actionSparkType: 'prompt',
    tags: ['Affirmations', 'Surprise', 'Written', 'Encouragement'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 445,
    commentsCount: 31,
    createdAt: '2025-02-09T00:00:00Z',
    updatedAt: '2025-02-09T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/27275285/pexels-photo-27275285.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/27275285/pexels-photo-27275285.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 2,
  },
  {
    id: 'post-41',
    sectionId: 'section-romantic-getaways',
    title: 'The Mountain Cabin Escape',
    body: 'We rented a cabin in the mountains for a long weekend. No WiFi, just hiking, stargazing, cooking together, and uninterrupted conversation. We came back feeling completely reset.',
    actionSparkText: 'Book a disconnected getaway in nature',
    actionSparkType: 'prompt',
    tags: ['Mountains', 'Cabin', 'Nature', 'Disconnect'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-16',
    authorDisplayName: '@cabinlove',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 512,
    commentsCount: 39,
    createdAt: '2025-02-10T00:00:00Z',
    updatedAt: '2025-02-10T00:00:00Z',
  },
  {
    id: 'post-42',
    sectionId: 'section-romantic-getaways',
    title: 'Road Trip to Nowhere',
    body: 'We got in the car with no destination, just snacks and a full tank. We stopped at random roadside attractions, took silly photos, and ended up at a small-town diner. It was spontaneous and perfect.',
    actionSparkText: 'Plan a spontaneous road trip with no fixed destination',
    actionSparkType: 'prompt',
    tags: ['Road Trip', 'Spontaneous', 'Adventure', 'Exploration'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: true,
    isWeeklyCurated: true,
    likes: 623,
    commentsCount: 51,
    createdAt: '2025-02-11T00:00:00Z',
    updatedAt: '2025-02-11T00:00:00Z',
  },
  {
    id: 'post-43',
    sectionId: 'section-just-because',
    title: 'Flowers on a Tuesday',
    body: 'I bought them flowers on a random Tuesday. Not for a birthday or anniversary—just because I saw their favorite kind at the store and thought of them. They said it meant more than any special occasion.',
    actionSparkText: 'Surprise your partner with flowers on a random day',
    actionSparkType: 'prompt',
    tags: ['Flowers', 'Surprise', 'Spontaneous', 'Thoughtful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-demo-17',
    authorDisplayName: '@tuesdayflowers',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 378,
    commentsCount: 26,
    createdAt: '2025-02-12T00:00:00Z',
    updatedAt: '2025-02-12T00:00:00Z',
  },
  {
    id: 'post-44',
    sectionId: 'section-just-because',
    title: 'The Lunch Note Surprise',
    body: 'I packed their lunch for work and hid a handwritten note inside that said "You\'re doing amazing. I\'m proud of you." They texted me a photo of it with heart emojis. Simple but powerful.',
    actionSparkText: 'Leave a surprise note in your partner\'s lunch or bag',
    actionSparkType: 'prompt',
    tags: ['Lunch', 'Note', 'Encouragement', 'Work'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: true,
    likes: 421,
    commentsCount: 30,
    createdAt: '2025-02-13T00:00:00Z',
    updatedAt: '2025-02-13T00:00:00Z',
  },
  {
    id: 'post-45',
    sectionId: 'section-date-night',
    title: 'The $20 “Yes Night”',
    body: 'One person sets a $20 cap. The other plans the whole vibe.',
    actionSparkText: 'Pick a $20 limit. Planner chooses: one bite, one sip, one tiny surprise. The only rule: say “yes” to the plan.',
    actionSparkType: 'prompt',
    tags: ['Budget-Friendly', 'Playful', 'Low-Effort'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 318,
    commentsCount: 22,
    createdAt: '2025-12-14T00:00:00Z',
    updatedAt: '2025-12-14T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/5779751/pexels-photo-5779751.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/5779751/pexels-photo-5779751.jpeg?auto=compress&cs=tinysrgb&w=800',
    thumbnailRank: 1,
  },
  {
    id: 'post-46',
    sectionId: 'section-date-night',
    title: 'Museum After Dark + One Secret Rule',
    body: 'Quiet rooms, big feelings—plus one rule that changes everything.',
    actionSparkText: 'Go to a museum/gallery. Rule: each of you chooses one piece the other has to interpret as “our relationship this month.” Share why.',
    actionSparkType: 'prompt',
    tags: ['Meaningful', 'Indoor', 'Conversation'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 287,
    commentsCount: 19,
    createdAt: '2025-12-15T00:00:00Z',
    updatedAt: '2025-12-15T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/3095534/pexels-photo-3095534.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/3095534/pexels-photo-3095534.jpeg?auto=compress&cs=tinysrgb&w=800',
    thumbnailRank: 2,
  },
  {
    id: 'post-47',
    sectionId: 'section-date-night',
    title: 'Two-Stop “Taste Tour”',
    body: 'Appetizer at one place, dessert at another—keep it moving.',
    actionSparkText: 'Pick 2 nearby spots. Stop 1: share one plate. Stop 2: dessert. Between stops, trade one compliment and one curiosity question.',
    actionSparkType: 'prompt',
    tags: ['Foodie', 'Weeknight', 'Easy'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 401,
    commentsCount: 35,
    createdAt: '2025-12-16T00:00:00Z',
    updatedAt: '2025-12-16T00:00:00Z',
  },
  {
    id: 'post-48',
    sectionId: 'section-date-night',
    title: 'The Thrifted Gift Challenge',
    body: 'Find each other a “perfectly wrong” gift in 10 minutes.',
    actionSparkText: 'Go to a thrift store. 10-minute timer. Budget: $10. Find a gift that says “I know you” (funny counts). Exchange + explain.',
    actionSparkType: 'prompt',
    tags: ['Playful', 'Budget-Friendly', 'Adventure'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 356,
    commentsCount: 28,
    createdAt: '2025-12-17T00:00:00Z',
    updatedAt: '2025-12-17T00:00:00Z',
  },
  {
    id: 'post-49',
    sectionId: 'section-date-night',
    title: 'Sunset Voice-Note Walk',
    body: 'A date with headphones… but it\'s your voice in them.',
    actionSparkText: 'Before you meet, each records a 60-second voice note: “One thing I\'ve been proud of you for lately.” Swap and listen on a sunset walk.',
    actionSparkType: 'prompt',
    tags: ['Romantic', 'Outdoor', 'Meaningful'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 512,
    commentsCount: 41,
    createdAt: '2025-12-18T00:00:00Z',
    updatedAt: '2025-12-18T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/9714370/pexels-photo-9714370.jpeg?auto=compress&cs=tinysrgb&w=400',
    mediaUrl: 'https://images.pexels.com/photos/9714370/pexels-photo-9714370.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 3,
  },
  {
    id: 'post-50',
    sectionId: 'section-date-night',
    title: 'Cook One Dish, Trade Roles',
    body: 'One cooks. One narrates like a TV host. Switch halfway.',
    actionSparkText: 'Choose one simple recipe. Person A cooks while Person B “hosts” (hype, questions, compliments). Switch roles midway. Plate it like a restaurant.',
    actionSparkType: 'prompt',
    tags: ['Cozy', 'Home', 'Laugh'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 439,
    commentsCount: 33,
    createdAt: '2025-12-19T00:00:00Z',
    updatedAt: '2025-12-19T00:00:00Z',
  },
  {
    id: 'post-51',
    sectionId: 'section-date-night',
    title: 'Recreate Your First Date—Wrong',
    body: 'Same theme, totally different execution. Chaos encouraged.',
    actionSparkText: 'Recreate the first date but with one twist: swap the location type (restaurant → picnic, bar → mocktail lounge at home). End by naming what you\'d keep forever.',
    actionSparkType: 'prompt',
    tags: ['Nostalgic', 'Romantic', 'Conversation'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 483,
    commentsCount: 37,
    createdAt: '2025-12-20T00:00:00Z',
    updatedAt: '2025-12-20T00:00:00Z',
  },
  {
    id: 'post-52',
    sectionId: 'section-date-night',
    title: 'The “No Phone” Photo Hunt',
    body: 'A mini scavenger hunt where the prize is attention.',
    actionSparkText: 'Phones stay in pocket except for camera. Capture 5 photos: “something that feels like us,” “a color that\'s your energy,” “a small joy,” “a future idea,” “a moment I want to remember.” Share after.',
    actionSparkType: 'prompt',
    tags: ['Presence', 'Outdoor', 'Creative'],
    source: 'curated',
    status: 'approved',
    authorDisplayName: 'Spark\'d Team',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 372,
    commentsCount: 26,
    createdAt: '2025-12-21T00:00:00Z',
    updatedAt: '2025-12-21T00:00:00Z',
  },
  {
    id: 'post-sv-1',
    sectionId: 'section-sweet-valentines',
    title: 'Love, Planned',
    body: 'I didn\'t want Valentine\'s Day to feel rushed or predictable. I planned it weeks ahead—every detail based on what makes us us. The timing wasn\'t accidental. Neither was the love.',
    actionSparkText: 'Plan Valentine\'s Day with intention—start early, think deeply',
    actionSparkType: 'prompt',
    tags: ['Planning', 'Intentional', 'Romance'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-sv-1',
    authorDisplayName: '@valentineplanner',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 384,
    commentsCount: 29,
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/3711652/pexels-photo-3711652.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/3711652/pexels-photo-3711652.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 1,
  },
  {
    id: 'post-sv-2',
    sectionId: 'section-sweet-valentines',
    title: 'A Valentine for the Future',
    body: 'Instead of focusing on just one night, I planned something that symbolized where we\'re going. Valentine\'s Day became less about gifts—and more about choosing each other again.',
    actionSparkText: 'Create a Valentine\'s gesture that looks ahead, not just at today',
    actionSparkType: 'prompt',
    tags: ['Future', 'Commitment', 'Meaningful'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-sv-2',
    authorDisplayName: '@futurevalentine',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 412,
    commentsCount: 33,
    createdAt: '2026-01-11T00:00:00Z',
    updatedAt: '2026-01-11T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/35567113/pexels-photo-35567113.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/35567113/pexels-photo-35567113.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 2,
  },
  {
    id: 'post-sv-3',
    sectionId: 'section-sweet-valentines',
    title: 'The City Was In On It',
    body: 'I turned the city into the plan—locations we love, moments we share, and one final stop that said everything I hadn\'t yet said out loud.',
    actionSparkText: 'Use places you love to tell your Valentine story',
    actionSparkType: 'prompt',
    tags: ['Surprise', 'Experience', 'Romantic'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-sv-3',
    authorDisplayName: '@citylove',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 356,
    commentsCount: 27,
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-01-12T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/35642035/pexels-photo-35642035.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/35642035/pexels-photo-35642035.jpeg?auto=compress&cs=tinysrgb&w=1200',
    thumbnailRank: 3,
  },
  {
    id: 'post-sv-4',
    sectionId: 'section-sweet-valentines',
    title: 'You Didn\'t Know I Saved That',
    body: 'They sent me a message once—just words, nothing fancy. I saved it. On Valentine\'s Day, I showed them I remembered what mattered.',
    actionSparkText: 'Turn a saved message into a meaningful Valentine\'s surprise',
    actionSparkType: 'prompt',
    tags: ['Listening', 'Memory', 'Emotional'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-sv-4',
    authorDisplayName: '@savedmoments',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 445,
    commentsCount: 38,
    createdAt: '2026-01-13T00:00:00Z',
    updatedAt: '2026-01-13T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/5728187/pexels-photo-5728187.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/5728187/pexels-photo-5728187.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
  {
    id: 'post-sv-5',
    sectionId: 'section-sweet-valentines',
    title: 'All Dressed Up',
    body: 'I told them to take the day for themselves—nails, hair, a little pampering. They thought it was just self-care before our date. The surprise was that the date was a professional photo shoot we\'d always talked about but never planned.',
    actionSparkText: 'Turn a day of self-care into a Valentine\'s surprise you\'ll remember forever',
    actionSparkType: 'prompt',
    tags: ['Surprise', 'Thoughtful', 'Romance'],
    source: 'user',
    status: 'approved',
    authorUserId: 'user-sv-5',
    authorDisplayName: '@photoshootlove',
    isTopStory: false,
    isWeeklyCurated: false,
    likes: 523,
    commentsCount: 42,
    createdAt: '2026-01-13T00:00:00Z',
    updatedAt: '2026-01-13T00:00:00Z',
    hasMedia: true,
    mediaType: 'image',
    mediaThumbnailUrl: 'https://images.pexels.com/photos/812258/pexels-photo-812258.jpeg?auto=compress&cs=tinysrgb&w=1200',
    mediaUrl: 'https://images.pexels.com/photos/812258/pexels-photo-812258.jpeg?auto=compress&cs=tinysrgb&w=1200',
  },
];
