import { CoachProfile, CalendarEvent } from '@/types';

export const SEED_COACHES: CoachProfile[] = [
  {
    id: 'coach-1',
    name: 'Dr. Sarah Lopez',
    photoUrl: 'https://i.pravatar.cc/300?img=1',
    credentials: 'LMFT • PhD in Clinical Psychology',
    specialty: 'Communication & Conflict Repair',
    bio: 'With over 15 years of experience, Dr. Lopez specializes in helping couples navigate difficult conversations and rebuild trust. Her approach combines evidence-based techniques with compassion and practical tools.',
    rating: 4.9,
    reviewCount: 132,
    tags: ['Communication', 'Conflict', 'Trust', 'Long-Distance'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 75 },
    ],
  },
  {
    id: 'coach-2',
    name: 'Marcus Chen',
    photoUrl: 'https://i.pravatar.cc/300?img=12',
    credentials: 'LPC • Certified Gottman Therapist',
    specialty: 'Intimacy & Emotional Connection',
    bio: 'Marcus brings a warm, authentic approach to helping couples deepen their emotional and physical intimacy. He believes in creating safe spaces where vulnerability can flourish.',
    rating: 4.8,
    reviewCount: 98,
    tags: ['Intimacy', 'Gratitude', 'Growth', 'Premarital'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 85 },
    ],
  },
  {
    id: 'coach-3',
    name: 'Dr. Aisha Patel',
    photoUrl: 'https://i.pravatar.cc/300?img=5',
    credentials: 'PsyD • Relationship Coach',
    specialty: 'Boundaries & Personal Growth',
    bio: 'Dr. Patel helps individuals and couples establish healthy boundaries while maintaining deep connection. Her holistic approach honors both personal growth and relationship health.',
    rating: 4.9,
    reviewCount: 156,
    tags: ['Boundaries', 'Growth', 'Communication', 'Rebuilding Trust'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 80 },
    ],
  },
  {
    id: 'coach-4',
    name: 'Jordan Reyes',
    photoUrl: 'https://i.pravatar.cc/300?img=33',
    credentials: 'LMFT • Trauma-Informed',
    specialty: 'Healing After Betrayal',
    bio: 'Jordan specializes in helping couples rebuild trust and heal from infidelity and betrayal. With a trauma-informed approach, they create a safe space for processing pain and finding a path forward.',
    rating: 4.7,
    reviewCount: 84,
    tags: ['Betrayal', 'Trust', 'Healing', 'Trauma'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 90 },
    ],
  },
  {
    id: 'coach-5',
    name: 'Elena Rossi',
    photoUrl: 'https://i.pravatar.cc/300?img=9',
    credentials: 'Relationship & Sex Therapist',
    specialty: 'Desire, Intimacy & Libido Mismatch',
    bio: 'Elena brings expertise in sexual health and intimacy to help couples navigate mismatched desire, rekindle passion, and build fulfilling intimate lives together.',
    rating: 4.8,
    reviewCount: 121,
    tags: ['Intimacy', 'Desire', 'Sexual Health', 'Communication'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 95 },
    ],
  },
  {
    id: 'coach-6',
    name: 'David Kim',
    photoUrl: 'https://i.pravatar.cc/300?img=15',
    credentials: 'LCSW • Couples & Families',
    specialty: 'Blended Families & Co-Parenting',
    bio: 'David has over a decade of experience helping blended families and co-parents navigate the unique challenges of combining households and raising children together.',
    rating: 4.7,
    reviewCount: 109,
    tags: ['Blended Families', 'Co-Parenting', 'Communication', 'Boundaries'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 80 },
    ],
  },
  {
    id: 'coach-7',
    name: 'Nia Thompson',
    photoUrl: 'https://i.pravatar.cc/300?img=20',
    credentials: 'Mindfulness-Based Relationship Coach',
    specialty: 'Emotional Regulation & Mindful Communication',
    bio: 'Nia integrates mindfulness practices with relationship coaching to help couples regulate emotions, communicate consciously, and build deeper presence with each other.',
    rating: 4.9,
    reviewCount: 143,
    tags: ['Mindfulness', 'Emotional Regulation', 'Communication', 'Stress'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 85 },
    ],
  },
  {
    id: 'coach-8',
    name: 'Rafael Alvarez',
    photoUrl: 'https://i.pravatar.cc/300?img=14',
    credentials: 'Certified Premarital Counselor',
    specialty: 'Engaged & Newlywed Couples',
    bio: 'Rafael helps engaged and newly married couples build a strong foundation by addressing expectations, communication patterns, and life planning before challenges arise.',
    rating: 4.8,
    reviewCount: 76,
    tags: ['Premarital', 'Communication', 'Expectations', 'Life Planning'],
    availableSessionTypes: [
      { id: 'intro-10', name: '10-min Intro Session', duration: 10, price: 0 },
      { id: 'full-30', name: '30-min Full Session', duration: 30, price: 70 },
    ],
  },
];

export const SEED_CALENDAR_EVENTS: Omit<CalendarEvent, 'id' | 'userId'>[] = [
  {
    type: 'date' as const,
    title: 'Wine & Tapas Date Night',
    description: 'Inspired by a Date Night idea from Inspo.',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    completed: false,
  },
  {
    type: 'coaching' as const,
    title: 'Intro Coaching Session with Dr. Lopez',
    description: 'Booked via Expert Coaching in Guidance.',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    time: '14:30',
    completed: false,
  },
  {
    type: 'special' as const,
    title: "Partner's Birthday",
    description: 'Plan something special.',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:00',
    completed: false,
  },
  {
    type: 'gamenight' as const,
    title: "7-Day Gratitude Challenge",
    description: 'From Community Challenge in Play tab.',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    time: '20:00',
    completed: false,
  },
  {
    type: 'workshops' as const,
    title: 'Communication Skills Workshop',
    description: 'Learning active listening techniques.',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:00',
    completed: false,
  },
  {
    type: 'special' as const,
    title: 'Anniversary Celebration',
    description: '2 years together!',
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    completed: false,
  },
  {
    type: 'date' as const,
    title: 'Sunset Picnic at the Park',
    description: 'Bring blanket and homemade snacks.',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    time: '17:30',
    completed: false,
  },
  {
    type: 'milestones' as const,
    title: 'Moving In Together',
    description: 'Lease starts today!',
    date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    time: '09:00',
    completed: false,
  },
  {
    type: 'date' as const,
    title: 'Cooking Class Together',
    description: 'Italian cuisine night.',
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    time: '18:30',
    completed: false,
  },
  {
    type: 'gamenight' as const,
    title: 'Board Game Night',
    description: 'Try the new card game we got.',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    time: '20:30',
    completed: false,
  },
  {
    type: 'milestones' as const,
    title: 'Job Promotion Celebration',
    description: "Celebrate partner's career milestone.",
    date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:30',
    completed: false,
  },
  {
    type: 'workshops' as const,
    title: 'Couples Yoga Workshop',
    description: 'Learning partner yoga poses and breathing.',
    date: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
    time: '10:00',
    completed: false,
  },
  {
    type: 'special' as const,
    title: 'First Date Anniversary',
    description: 'Revisit where we first met.',
    date: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    time: '19:00',
    completed: false,
  },
  {
    type: 'date' as const,
    title: 'Stargazing at the Lake',
    description: 'Bring telescope and blankets.',
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000).toISOString(),
    time: '21:00',
    completed: false,
  },
  {
    type: 'coaching' as const,
    title: 'Follow-up Session with Marcus',
    description: 'Intimacy & Connection check-in.',
    date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    time: '16:00',
    completed: false,
  },
];
